(function() {
var _UDS_CONST_LOCALE = 'en';
var _UDS_CONST_SHORT_DATE_PATTERN = 'MDY'; 
var _UDS_MSG_SEARCHER_IMAGE = ('Image'); 
var _UDS_MSG_SEARCHER_WEB = ('Web'); 
var _UDS_MSG_SEARCHER_BLOG = ('Blog'); 
var _UDS_MSG_SEARCHER_VIDEO = ('Video'); 
var _UDS_MSG_SEARCHER_LOCAL = ('Local'); 
var _UDS_MSG_SEARCHCONTROL_SAVE = ('save'); 
var _UDS_MSG_SEARCHCONTROL_KEEP = ('keep'); 
var _UDS_MSG_SEARCHCONTROL_INCLUDE = ('include'); 
var _UDS_MSG_SEARCHCONTROL_COPY = ('copy'); 
var _UDS_MSG_SEARCHCONTROL_CLOSE = ('close'); 
var _UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS = ('Sponsored Links'); 
var _UDS_MSG_SEARCHCONTROL_SEE_MORE = ('see more...'); 
var _UDS_MSG_SEARCHCONTROL_WATERMARK = ('clipped from Google'); 
var _UDS_MSG_SEARCHER_CONFIG_SET_LOCATION = ('Search location'); 
var _UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP = ('Disable address lookup'); 
var _UDS_MSG_SEARCHER_NEWS = ('News'); 
function _UDS_MSG_MINUTES_AGO(AGE_MINUTES_AGO) {return ('' + AGE_MINUTES_AGO + ' minutes ago');} 
var _UDS_MSG_ONE_HOUR_AGO = ('1 hour ago'); 
function _UDS_MSG_HOURS_AGO(AGE_HOURS_AGO) {return ('' + AGE_HOURS_AGO + ' hours ago');} 
function _UDS_MSG_NEWS_ALL_N_RELATED(NUMBER) {return ('all ' + NUMBER + ' related');} 
var _UDS_MSG_NEWS_RELATED = ('Related Articles'); 
var _UDS_MSG_BRANDING_STRING = ('powered by Google'); 
var _UDS_MSG_SORT_BY_DATE = ('Sort by date'); 
var _UDS_MSG_MONTH_ABBR_JAN = ('Jan'); 
var _UDS_MSG_MONTH_ABBR_FEB = ('Feb'); 
var _UDS_MSG_MONTH_ABBR_MAR = ('Mar'); 
var _UDS_MSG_MONTH_ABBR_APR = ('Apr'); 
var _UDS_MSG_MONTH_ABBR_MAY = ('May'); 
var _UDS_MSG_MONTH_ABBR_JUN = ('Jun'); 
var _UDS_MSG_MONTH_ABBR_JUL = ('Jul'); 
var _UDS_MSG_MONTH_ABBR_AUG = ('Aug'); 
var _UDS_MSG_MONTH_ABBR_SEP = ('Sep'); 
var _UDS_MSG_MONTH_ABBR_OCT = ('Oct'); 
var _UDS_MSG_MONTH_ABBR_NOV = ('Nov'); 
var _UDS_MSG_MONTH_ABBR_DEC = ('Dec'); 
var _UDS_MSG_DIRECTIONS = ('directions'); 
var _UDS_MSG_CLEAR_RESULTS = ('clear results'); 
var _UDS_MSG_SHOW_ONE_RESULT = ('show one result'); 
var _UDS_MSG_SHOW_MORE_RESULTS = ('show more results'); 
var _UDS_MSG_SHOW_ALL_RESULTS = ('show all results'); 
var _UDS_MSG_SETTINGS = ('settings'); 
var _UDS_MSG_SEARCH = ('search'); 
var _UDS_MSG_SEARCH_UC = ('Search'); 
var _UDS_MSG_POWERED_BY = ('powered by'); 
function _UDS_MSG_LOCAL_ATTRIBUTION(LOCAL_RESULTS_PROVIDER) {return ('Business listings provided by ' + LOCAL_RESULTS_PROVIDER + '');} 
var _UDS_MSG_SEARCHER_BOOK = ('Book'); 
function _UDS_MSG_FOUND_ON_PAGE(FOUND_ON_PAGE) {return ('Page ' + FOUND_ON_PAGE + '');} 
function _UDS_MSG_TOTAL_PAGE_COUNT(PAGE_COUNT) {return ('' + PAGE_COUNT + ' pages');} 
var _UDS_MSG_SEARCHER_BY = ('by'); 
var _UDS_MSG_SEARCHER_CODE = ('Code'); 
var _UDS_MSG_UNKNOWN_LICENSE = ('Unknown License'); 
var _UDS_MSG_SEARCHER_GSA = ('Search Appliance'); 
var _UDS_MSG_SEARCHCONTROL_MORERESULTS = ('More results'); 
var _UDS_MSG_SEARCHCONTROL_PREVIOUS = ('Previous'); 
var _UDS_MSG_SEARCHCONTROL_NEXT = ('Next'); 
var _UDS_MSG_GET_DIRECTIONS = ('Get directions'); 
var _UDS_MSG_GET_DIRECTIONS_TO_HERE = ('To here'); 
var _UDS_MSG_GET_DIRECTIONS_FROM_HERE = ('From here'); 
var _UDS_MSG_CLEAR_RESULTS_UC = ('Clear results'); 
var _UDS_MSG_SEARCH_THE_MAP = ('search the map'); 
var _UDS_MSG_SCROLL_THROUGH_RESULTS = ('scroll through results'); 
var _UDS_MSG_EDIT_TAGS = ('edit tags'); 
var _UDS_MSG_TAG_THIS_SEARCH = ('tag this search'); 
var _UDS_MSG_SEARCH_STRING = ('search string'); 
var _UDS_MSG_OPTIONAL_LABEL = ('optional label'); 
var _UDS_MSG_DELETE = ('delete'); 
var _UDS_MSG_DELETED = ('deleted'); 
var _UDS_MSG_CANCEL = ('cancel'); 
var _UDS_MSG_UPLOAD_YOUR_VIDEOS = ('upload your own video'); 
var _UDS_MSG_IM_DONE_WATCHING = ('i\047m done watching this'); 
var _UDS_MSG_CLOSE_VIDEO_PLAYER = ('close video player'); 
var _UDS_MSG_NO_RESULTS = ('No Results'); 
var _UDS_MSG_LINKEDCSE_ERROR_RESULTS = ('This Custom Search Engine is loading. Try again in a few seconds.'); 
var _UDS_MSG_COUPONS = ('Coupons'); 
var _UDS_MSG_BACK = ('back'); 
var _UDS_MSG_SUBSCRIBE = ('Subscribe'); 
var _UDS_MSG_SEARCHER_PATENT = ('Patent'); 
var _UDS_MSG_USPAT = ('US Pat.'); 
var _UDS_MSG_USPAT_APP = ('US Pat. App'); 
var _UDS_MSG_PATENT_FILED = ('Filed'); 
var _UDS_MSG_ADS_BY_GOOGLE = ('Ads by Google'); 
var _UDS_MSG_SET_DEFAULT_LOCATION = ('Set default location'); 
var _UDS_MSG_NEWSCAT_TOPSTORIES = ('Top Stories'); 
var _UDS_MSG_NEWSCAT_WORLD = ('World'); 
var _UDS_MSG_NEWSCAT_NATION = ('Nation'); 
var _UDS_MSG_NEWSCAT_BUSINESS = ('Business'); 
var _UDS_MSG_NEWSCAT_SCITECH = ('Sci/Tech'); 
var _UDS_MSG_NEWSCAT_ENTERTAINMENT = ('Entertainment'); 
var _UDS_MSG_NEWSCAT_HEALTH = ('Health'); 
var _UDS_MSG_NEWSCAT_SPORTS = ('Sports'); 
var _UDS_MSG_NEWSCAT_POLITICS = ('Politics');
var b=true,c=null,g=false,i=encodeURIComponent,j=google_exportSymbol,aa=_UDS_CONST_SHORT_DATE_PATTERN,k=window,m=google,ba=navigator,o=undefined,ca=parseInt,da=parseFloat,ea=_UDS_CONST_LOCALE,p=document,fa=decodeURIComponent,q=Math;function ga(a,d){return a.onload=d}function ha(a,d){return a.onreadystatechange=d}function r(a,d){return a.title=d}function s(a,d){return a.className=d}function ia(a,d){return a.input=d}function ja(a,d){return a.width=d}function ka(a,d){return a.checked=d}
function t(a,d){return a.innerHTML=d}function la(a,d){return a.value=d}function ma(a,d){return a.type=d}function na(a,d){return a.onclick=d}function oa(a,d){return a.display=d}function pa(a,d){return a.execute=d}function u(a,d){return a.height=d}function qa(a,d){return a.visibility=d}
var v="appendChild",ra="push",w="length",sa="title",x="prototype",y="cursor",ta="className",ua="clearTimeout",A="input",C="width",va="Version",wa="round",ya="checked",za="setTimeout",D="replace",Aa="document",Ba="split",Ca="floor",Da="content",Ea="userAgent",Fa="value",Ga="location",Ha="indexOf",Ia="getComputedStyle",E="style",Ja="close",F="search",G="call",Ka="match",La="readyState",Ma="focus",H="createElement",I="setAttribute",J="loader",Na="currentStyle",Oa="cloneNode",Pa="action",Qa="type",Ra=
"apply",Sa="recordStat",Ta="ServiceBase",K="CurrentLocale",L="execute",Ua="height",Va="getTime",Wa="toLowerCase",M;if(!m[F].NoOldNames){j("UDS_ServiceBase",m[J][Ta]);j("UDS_OriginalAppPath",m[J].OriginalAppPath);j("UDS_ApiKey",m[J].ApiKey);j("UDS_KeyVerified",m[J].KeyVerified);j("UDS_LoadFailure",m[J].LoadFailure);j("UDS_CurrentLocale",ea);j("UDS_ShortDatePattern",aa);j("UDS_Version",m[F][va]);j("UDS_JSHash",m[F].JSHash)}if(!N)var N=j;if(!O)var O=google_exportProperty;var P={};P.blank="&nbsp;";P.image=_UDS_MSG_SEARCHER_IMAGE;P.web=_UDS_MSG_SEARCHER_WEB;P.blog=_UDS_MSG_SEARCHER_BLOG;P.video=_UDS_MSG_SEARCHER_VIDEO;P.local=_UDS_MSG_SEARCHER_LOCAL;P.news=_UDS_MSG_SEARCHER_NEWS;P.book=_UDS_MSG_SEARCHER_BOOK;P.patent="Patent";P["ads-by-google"]=_UDS_MSG_ADS_BY_GOOGLE;P.cse="Custom Search Control";P.save=_UDS_MSG_SEARCHCONTROL_SAVE;P.keep=_UDS_MSG_SEARCHCONTROL_KEEP;P.include=_UDS_MSG_SEARCHCONTROL_INCLUDE;P.copy=_UDS_MSG_SEARCHCONTROL_COPY;P.close=_UDS_MSG_SEARCHCONTROL_CLOSE;
P["sponsored-links"]=_UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS;P["see-more"]=_UDS_MSG_SEARCHCONTROL_SEE_MORE;P.watermark=_UDS_MSG_SEARCHCONTROL_WATERMARK;P["search-location"]=_UDS_MSG_SEARCHER_CONFIG_SET_LOCATION;P["disable-address-lookup"]=_UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP;P["sort-by-date"]=_UDS_MSG_SORT_BY_DATE;P.pbg=_UDS_MSG_BRANDING_STRING;P["n-minutes-ago"]=_UDS_MSG_MINUTES_AGO;P["n-hours-ago"]=_UDS_MSG_HOURS_AGO;P["one-hour-ago"]=_UDS_MSG_ONE_HOUR_AGO;P["all-n-related"]=_UDS_MSG_NEWS_ALL_N_RELATED;
P["related-articles"]=_UDS_MSG_NEWS_RELATED;P["page-count"]=_UDS_MSG_TOTAL_PAGE_COUNT;var Q=[];Q[0]=_UDS_MSG_MONTH_ABBR_JAN;Q[1]=_UDS_MSG_MONTH_ABBR_FEB;Q[2]=_UDS_MSG_MONTH_ABBR_MAR;Q[3]=_UDS_MSG_MONTH_ABBR_APR;Q[4]=_UDS_MSG_MONTH_ABBR_MAY;Q[5]=_UDS_MSG_MONTH_ABBR_JUN;Q[6]=_UDS_MSG_MONTH_ABBR_JUL;Q[7]=_UDS_MSG_MONTH_ABBR_AUG;Q[8]=_UDS_MSG_MONTH_ABBR_SEP;Q[9]=_UDS_MSG_MONTH_ABBR_OCT;Q[10]=_UDS_MSG_MONTH_ABBR_NOV;Q[11]=_UDS_MSG_MONTH_ABBR_DEC;P["month-abbr"]=Q;P.directions=_UDS_MSG_DIRECTIONS;
P["clear-results"]=_UDS_MSG_CLEAR_RESULTS;P["show-one-result"]=_UDS_MSG_SHOW_ONE_RESULT;P["show-more-results"]=_UDS_MSG_SHOW_MORE_RESULTS;P["show-all-results"]=_UDS_MSG_SHOW_ALL_RESULTS;P.settings=_UDS_MSG_SETTINGS;P.search=_UDS_MSG_SEARCH;P["search-uc"]=_UDS_MSG_SEARCH_UC;P["powered-by"]=_UDS_MSG_POWERED_BY;P.sa=_UDS_MSG_SEARCHER_GSA;P.by=_UDS_MSG_SEARCHER_BY;P.code=_UDS_MSG_SEARCHER_CODE;P["unknown-license"]=_UDS_MSG_UNKNOWN_LICENSE;P["more-results"]=_UDS_MSG_SEARCHCONTROL_MORERESULTS;
P.previous=_UDS_MSG_SEARCHCONTROL_PREVIOUS;P.next=_UDS_MSG_SEARCHCONTROL_NEXT;P["get-directions"]=_UDS_MSG_GET_DIRECTIONS;P["to-here"]=_UDS_MSG_GET_DIRECTIONS_TO_HERE;P["from-here"]=_UDS_MSG_GET_DIRECTIONS_FROM_HERE;P["clear-results-uc"]=_UDS_MSG_CLEAR_RESULTS_UC;P["search-the-map"]=_UDS_MSG_SEARCH_THE_MAP;P["scroll-results"]=_UDS_MSG_SCROLL_THROUGH_RESULTS;P["edit-tags"]=_UDS_MSG_EDIT_TAGS;P["tag-search"]=_UDS_MSG_TAG_THIS_SEARCH;P["search-string"]=_UDS_MSG_SEARCH_STRING;P["optional-label"]=_UDS_MSG_OPTIONAL_LABEL;
P["delete"]=_UDS_MSG_DELETE;P.deleted=_UDS_MSG_DELETED;P.cancel=_UDS_MSG_CANCEL;P["upload-video"]=_UDS_MSG_UPLOAD_YOUR_VIDEOS;P["im-done"]=_UDS_MSG_IM_DONE_WATCHING;P["close-player"]=_UDS_MSG_CLOSE_VIDEO_PLAYER;P["no-results"]=_UDS_MSG_NO_RESULTS;P["linked-cse-error-results"]=_UDS_MSG_LINKEDCSE_ERROR_RESULTS;P.back=_UDS_MSG_BACK;P.subscribe=_UDS_MSG_SUBSCRIBE;P["us-pat"]="US Pat.";P["us-pat-app"]="US Pat. App";P["us-pat-filed"]="Filed";function Xa(a,d){var e=function(){};e.prototype=d[x];a.prototype=new e;a[x].tg=function(f){var h=Array[x].splice[Ra](arguments,[1,arguments[w]]);return f[Ra](a,h)}}var _json_cache_defeater_=(new Date)[Va](),_json_request_require_prep=b;function Ya(a,d){if(Za("msie")&&$a("msie 6.0")){a=R(this,ab,[a,d]);k[za](a,0)}else ab(a,d)}function bb(a){_json_request_require_prep=g;Ya(a,c);_json_request_require_prep=b}
function ab(a,d){var e=p.getElementsByTagName("head")[0];e||(e=p.body.parentNode[v](p[H]("head")));var f=p[H]("script");ma(f,"text/javascript");f.charset="utf-8";a=_json_request_require_prep?a+"&key="+m[J].ApiKey+"&v="+d:a;if(cb()||db())a=a+"&nocache="+_json_cache_defeater_++;f.src=a;var h=function(){ga(f,c);f.parentNode.removeChild(f);delete f};a=function(l){l=l?l:k.event;l=l.target?l.target:l.srcElement;if(l[La]=="loaded"||l[La]=="complete"){ha(l,c);h()}};if(ba.product=="Gecko")ga(f,h);else ha(f,
a);e[v](f)}function eb(a,d){return function(){return d[Ra](a,arguments)}}function R(a,d,e){return function(){return d[Ra](a,e)}}function fb(a){for(;a.firstChild;)a.removeChild(a.firstChild)}function T(a,d){try{a[v](d)}catch(e){}return d}function U(a,d){var e=p[H]("div");if(a)t(e,a);if(d)s(e,d);return e}function W(a){var d=p[H]("div");if(a)s(d,a);return d}function gb(a,d){var e=p[H]("span");a&&T(e,p.createTextNode(a?a:""));if(d)s(e,d);return e}
function hb(a,d,e){var f=p[H]("table");f[I]("cellSpacing",a?a:0);f[I]("cellPadding",d?d:0);if(e)s(f,e);return f}function ib(a,d,e){(a=a.insertRow(-1))||alert(a);for(var f=0;f<d;f++)X(a,e);return a}function X(a,d){a=a.insertCell(-1);if(d)s(a,d);return a}function jb(a){var d=p[H]("td");if(a)s(d,a);return d}function kb(a,d,e,f){var h=p[H]("img");h.src=a;if(d)ja(h,d);if(e)u(h,e);if(f)s(h,f);return h}
function lb(a,d,e,f,h){var l=p[H]("a");l.href=a;if(d)f?T(l,gb(d,f)):T(l,p.createTextNode(d?d:""));if(e)l.target=e;if(h)r(l,h);return l}function Y(a,d,e,f,h){var l=U(c,f),n=p[H]("a");n.href=a;t(n,d);if(f)s(n,f);if(e)n.target=e;if(h)r(n,h);l[v](n);return l}function mb(a){var d=p[H]("form");if(a)s(d,a);return d}function nb(a,d){var e=p[H]("input");ma(e,"submit");la(e,a);if(d)s(e,d);return e}
function ob(a,d,e){var f=p[H]("input");f[I]("autoComplete","off");ma(f,"text");if(a==-1)Z(f,"util-css-expand");else f.size=a>0?a:10;d&&pb(f,d);if(e)la(f,e);return f}function qb(a,d,e,f){var h=p[H]("input");ma(h,"checkbox");h.name=a;la(h,d);if(f)s(h,f);if(e)ka(h,e);return h}function rb(a,d){s(a,d)}function pb(a,d){Z(a,d)}function sb(a,d){$(a,d)}function Z(a,d){var e;a:{if(!(a==c||a[ta]==c)){e=a[ta][Ba](" ");for(var f=0;f<e[w];f++)if(e[f]==d){e=b;break a}}e=g}e||(a.className+=" "+d)}
function $(a,d){if(a[ta]!=c){for(var e=a[ta][Ba](" "),f=[],h=g,l=0;l<e[w];l++)if(e[l]!=d)e[l]&&f[ra](e[l]);else h=b;if(h)s(a,f.join(" "))}}function tb(a){if(ub!="")return ub;var d=a[Wa]()[Ba](".");if(d[w]<2)ub=".com";a=d.pop();d=d.pop();return ub=a[w]==2?vb[d]&&vb[d][a]==1?"."+d+"."+a:"."+a:".com"}
var ub="",vb={ef:{Dg:1,Hg:1,Pg:1,id:1,Qg:1,"in":1,Sg:1,Ug:1,Vg:1,Wg:1,Zg:1,ih:1,xh:1,Bh:1,Ch:1,Gh:1,Hh:1,Kh:1},Eg:{ug:1,xg:1,zg:1,Ag:1,Bg:1,Cg:1,ef:1,Ig:1,"do":1,Jg:1,Kg:1,Lg:1,Mg:1,Ng:1,Og:1,Tg:1,$g:1,ah:1,bh:1,dh:1,eh:1,fh:1,gh:1,hh:1,kh:1,lh:1,mh:1,nh:1,oh:1,ph:1,sh:1,uh:1,wh:1,yh:1,zh:1,Ah:1,Eh:1,Fh:1,Jh:1},jh:{vg:1}};function Za(a){if(a in wb)return wb[a];return wb[a]=ba[Ea][Wa]()[Ha](a)!=-1}function $a(a){if(a in xb)return xb[a];return xb[a]=ba.appVersion[Wa]()[Ha](a)!=-1}var wb={},xb={};
function cb(){return Za("msie")}function db(){return Za("safari")||Za("konqueror")}var yb,zb,Ab,Bb,Cb,Db,Eb;if(k.sg){yb=b;if(k.XMLHttpRequest)zb=b;else Ab=b}else if(k.opera)Bb=b;else if(p.childNodes&&!p.all&&!ba.taintEnabled){Cb=b;if(ba[Ea][Ha]("iPhone")>0)Db=b}else if(p.getBoxObjectFor!=c)Eb=b;
function Fb(a){this.ac=a+"branding";this.Rb=a+"branding-vertical";this.Rg=a+"branding-img";this.Dh=a+"branding-user-defined";this.je=a+"branding-img-noclear";this.df=a+"branding-clickable";this.text=a+"branding-text"};m[F].a=function(){this.fa=this.Fg=c;this.Dc=this.og=0;this.fe=b;this.M={width:100,height:75};this.Ea=m[F].a.bb;this.ne=1;this.W(m[F].a.da);this.Vd();this.gwsUrl=this.u=this.H=this.th=this.w=this.Jb=this.Ab=this.$a=this.sc=this.Ob=this.hc=this.fc=c;this.oa=[];this.he=typeof k==="object"&&k[Ga]&&k[Ga].hostname&&k[Ga].hostname!=""?tb(k[Ga].hostname):".com";this.pb=this.jb=c};N("google.search.Search",m[F].a);m[F].a.Hc=m[J][Ta];O(m[F].a,"BASE",m[F].a.Hc);m[F].a.ra="large";O(m[F].a,"LARGE_RESULTSET",m[F].a.ra);
m[F].a.da="small";O(m[F].a,"SMALL_RESULTSET",m[F].a.da);m[F].a.Bb="filtered_cse";O(m[F].a,"FILTERED_CSE_RESULTSET",m[F].a.Bb);m[F].a.Ke=8;O(m[F].a,"LARGE_RESULTS",m[F].a.Ke);m[F].a.Te=4;O(m[F].a,"SMALL_RESULTS",m[F].a.Te);m[F].a.Ee=10;O(m[F].a,"FILTERED_CSE_RESULTS",m[F].a.Ee);m[F].a.md=5000;O(m[F].a,"KEEP_SWEEPER_DELAY",m[F].a.md);m[F].a.Ne="_top";O(m[F].a,"LINK_TARGET_TOP",m[F].a.Ne);m[F].a.Me="_self";O(m[F].a,"LINK_TARGET_SELF",m[F].a.Me);m[F].a.Le="_parent";O(m[F].a,"LINK_TARGET_PARENT",m[F].a.Le);
m[F].a.bb="_blank";O(m[F].a,"LINK_TARGET_BLANK",m[F].a.bb);m[F].a.cb="order-by-relevance";O(m[F].a,"ORDER_BY_RELEVANCE",m[F].a.cb);m[F].a.la="order-by-date";O(m[F].a,"ORDER_BY_DATE",m[F].a.la);m[F].a.pd="order-by-ascending-date";O(m[F].a,"ORDER_BY_ASCENDING_DATE",m[F].a.pd);m[F].a.Cb="restrict-type";O(m[F].a,"RESTRICT_TYPE",m[F].a.Cb);m[F].a.Tb="restrict-safesearch";O(m[F].a,"RESTRICT_SAFESEARCH",m[F].a.Tb);m[F].a.Vb="active";O(m[F].a,"SAFESEARCH_STRICT",m[F].a.Vb);m[F].a.Ub="off";
O(m[F].a,"SAFESEARCH_OFF",m[F].a.Ub);m[F].a.yd="moderate";O(m[F].a,"SAFESEARCH_MODERATE",m[F].a.yd);m[F].a.Ma="restrict-extended";O(m[F].a,"RESTRICT_EXTENDED_ARGS",m[F].a.Ma);m[F].a.ig=P;O(m[F].a,"strings",m[F].a.ig);m[F].a[x].Of=function(){var a=this.ma+"?hl="+m[F][K]+"&source=uds";a+=this.u?this.u:"&q=";return this.wa&&this.wa!=""?this.wa:a};m[F].a[x].ag=function(a){this.H=a==c||a==""?c:a};O(m[F].a[x],"setQueryAddition",m[F].a[x].ag);
m[F].a[x].ya=function(a,d,e){a=m[F].a.Hc+this.Aa+"?callback="+a+"&context="+d+"&lstkp="+this.cf()+"&rsz="+this.Ga+"&hl="+m[F][K];if(this.ub)a+="&source="+i(this.ub);if(this.he)a+="&gss="+this.he;if(m[F].JSHash)a+="&sig="+m[F].JSHash;if(e)a+="&start="+e;return a};m[F].a[x].eg=function(a){this.ub=a};O(m[F].a[x],"setSearcherSrc",m[F].a[x].eg);m[F].a[x].vb=function(a){this.Ea=a};O(m[F].a[x],"setLinkTarget",m[F].a[x].vb);M=m[F].a[x];M.s=function(){return this.Ea&&this.Ea!=""?this.Ea:c};
M.yf=function(){this.og++;this.Dc++;this.Jb&&k[ua](this.Jb);this.Jb=k[za](R(this,this[L],[c]),m[F].a.md)};M.cf=function(){k[ua](this.Jb);var a=this.Dc;this.Dc=0;return a};M.mc=function(){if(this.fc==c)this.fc="gsc-"+this.w+"Result";return this.fc};M.ia=function(){if(this.hc==c)this.hc="gs-"+this.w+"Result";return this.hc};M.vf=function(){if(this.Ob==c)this.Ob=P[this.w];return this.$a?this.$a:this.Ob};M.tf=function(){if(this.sc==c)this.sc=P[this.w];return this.$a?this.$a:this.sc};M.uf=function(){return this.Ga};
O(m[F].a[x],"getResultSetSize",m[F].a[x].uf);m[F].a[x].W=function(a){switch(a){case m[F].a.ra:this.Ga=m[F].a.ra;break;default:case m[F].a.da:this.Ga=m[F].a.da;break}};O(m[F].a[x],"setResultSetSize",m[F].a[x].W);pa(m[F].a[x],function(a){var d=(new Date)[Va]();this.Cc=d%100==1?d:-1;d=this.ha(a,c,c);d+=this.Va?"&"+this.Va:"";if(k._googleudsextrastuff)d+=k._googleudsextrastuff;this.cursor=c;this.Cf=a;Ya(d,m[F][va]);if(this.oa&&this.oa[w]>0)for(d=0;d<this.oa[w];d++)this.oa[d][L](a)});
O(m[F].a[x],"execute",m[F].a[x][L]);m[F].a[x].ie=function(a){if(this[y]&&a<this[y].pages[w]){a=this.ha(this.Cf,c,c,this[y].pages[a].start);this.cursor=c;Ya(a,m[F][va])}};O(m[F].a[x],"gotoPage",m[F].a[x].ie);m[F].a[x].Ve=function(a){this.oa&&this.oa[ra](a)};O(m[F].a[x],"addRelatedSearcher",m[F].a[x].Ve);m[F].a[x].sf=function(a,d,e){return this.ha(a,d,e)+"&key="+m[J].ApiKey+"&v="+m[F][va]};O(m[F].a[x],"getExecuteUrl",m[F].a[x].sf);
m[F].a[x].ta=function(a){var d=P.watermark+" - "+this.ff();d=Y("http://code.google.com/apis/ajaxsearch/faq.html",d,"_blank","gs-watermark");T(a,d)};m[F].a[x].ff=function(){var a=new Date;return a.getMonth()+1+"/"+a.getFullYear()};
m[F].a[x].Ua=function(a){var d;d=a.getFullYear();var e=a.getMonth(),f=P["month-abbr"][e];a=a.getDate();if(a<10)a="0"+a;switch(m[F].ShortDatePattern){case "MDY":d=f+" "+a+", "+d;break;case "YMD":if(m[F][K]=="zh-CN"||m[F][K]=="zh-TW"||m[F][K]=="ja"||m[F][K]=="ko"){f=Gb[m[F][K]];d=d+f.year+(e+1)+f.month+a+f.day}else d=d+" "+f+" "+a;break;default:case "DMY":d=a+" "+f+" "+d;break}return d};O(m[F].a[x],"formatToShortDate",m[F].a[x].Ua);
var Gb={"zh-CN":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},"zh-TW":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},ja:{month:"\u6708",year:"\u5e74",day:"\u65e5"},ko:{month:" \uc6d4 ",year:" \ub144 ",day:" \uc77c "}};m[F].a.nd=3600000;m[F].a.Se=60000;m[F].a.Re=86400000;
m[F].a[x].lc=function(a){var d=(new Date)[Va](),e=a[Va]();if(d<e)return P["n-minutes-ago"](2);d=d-e;if(d<m[F].a.nd){a=q[Ca](d/m[F].a.Se);a=a<=1?2:a;return P["n-minutes-ago"](a)}if(d<m[F].a.Re){a=q[Ca](d/m[F].a.nd);if(a<=1)return P["one-hour-ago"];else{a=a;return P["n-hours-ago"](a)}}return this.Ua(a)};O(m[F].a[x],"formatToRelativeDate",m[F].a[x].lc);m[F].a[x].Vd=function(){this.qh=this.gwsUrl=c;this.results=[]};O(m[F].a[x],"clearResults",m[F].a[x].Vd);
m[F].a[x].nf=function(){this.Wd&&this.Wd();if(this.Cc!=-1){m[J][Sa]("asa_"+this.w,"req."+((new Date)[Va]()-this.Cc),b);this.Cc=-1}};
m[F].a[x].V=function(a,d,e,f){if(!(a==c&&d==204)){this.gwsUrl=c;if(this.results&&this.results[w]>0)for(var h=0;h<this.results[w];h++)this.results[h].html&&Hb(this.results[h].html);if(a&&a.results&&a.results[w]>0){this.results=a.results;if(a[y]&&a[y].moreResultsUrl)this.gwsUrl=this.wa&&this.wa!=""?this.wa:a[y].moreResultsUrl;else if(this.u&&this.ma)this.gwsUrl=this.Of()}else this.results=[];this.completionStatus=d;this.hashStatus=f;this.Gg=e;this.qe=a&&a.resultAttribution&&a.resultAttribution!=c&&
a.resultAttribution!=""?a.resultAttribution:c;if(a&&a[y]&&a[y].pages&&a[y].pages[w]>0)this.cursor=a[y];else typeof this[y]!="undefined"&&delete this[y];if(a&&a.context)this.context=a.context;else typeof this.context!="undefined"&&delete this.context;if(a&&a.promotions)this.promotions=a.promotions;else typeof this.promotions!="undefined"&&delete this.promotions;if(a&&a.omittedResults)this.omittedResults=a.omittedResults;else typeof this.omittedResults!="undefined"&&delete this.omittedResults;this.fe&&
this.Ye();this.nf()}};O(m[F].a[x],"onSearchComplete",m[F].a[x].V);m[F].a[x].ge=function(){var a=c;if(this.qe)a=U(this.qe,"gs-results-attribution");return a};O(m[F].a[x],"getAttribution",m[F].a[x].ge);m[F].a[x].Ye=function(){var a,d;for(a=0;a<this.results[w];a++){d=this.results[a];this.C(d)}};m[F].a[x].xb=function(a,d,e){e||(e=[c]);this.Wd=R(a,d,e)};O(m[F].a[x],"setSearchCompleteCallback",m[F].a[x].xb);
m[F].a.ka=function(a,d){var e=g,f;if(a[w])for(var h=0;h<a[w];h++)if(a[h]==c){a[h]=d;f=h;e=b;break}if(!e){f=a[w];a[ra](d)}return f};O(m[F].a,"AllocateCompletionMapContext",m[F].a.ka);m[F].a[x].zb=function(a){this.$a=a};O(m[F].a[x],"setUserDefinedLabel",m[F].a[x].zb);m[F].a[x].gg=function(a){this.Ab=a};O(m[F].a[x],"setUserDefinedClassSuffix",m[F].a[x].gg);m[F].a[x].Zf=function(){this.fe=g};O(m[F].a[x],"setNoHtmlGeneration",m[F].a[x].Zf);
m[F].a.Ya=function(a,d,e,f,h){var l=q.min(e[C]/a,e[Ua]/d);l=q.min(l,1);var n={};ja(n,q[wa](a*l));u(n,q[wa](d*l));if(f){ja(f,n[C]);u(f,n[Ua]);if(h)f[E].left=(e[C]-n[C])/2+"px"}return n};O(m[F].a,"scaleImage",m[F].a.Ya);m[F].a.Od=1;O(m[F].a,"VERTICAL_BRANDING",m[F].a.Od);m[F].a.Fe=2;O(m[F].a,"HORIZONTAL_BRANDING",m[F].a.Fe);
m[F].a.qf=function(a,d,e){var f=d&&d==m[F].a.Od,h=new Fb("gsc-");d=W(h.ac);var l=hb(c,c,h.ac);T(d,l);f=!f;if(!f){Z(d,h.Rb);Z(l,h.Rb)}var n=ib(l,0),z,B;if(f)B=z=n;else{z=n;B=ib(l,0)}var V="/css/small-logo.png",S=51;n=15;if(e)if(typeof e=="string")if(e[Ka](/^http:\/\/www\.youtube\.com/)){V="/css/youtube-logo-55x24.png";S=55;n=24;Z(d,h.ac+"-youtube");if(!f){Z(d,h.Rb+"-youtube");Z(l,h.Rb+"-youtube")}}f=X(z,h.text);l=X(B,h.je);z=U(P["powered-by"],h.text);V=m[J][Ta]+V;S=S;n=n;B=h.je;if(yb&&!zb){B=W(B);
B[E].filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+V+'")';ja(B[E],S+"px");u(B[E],n+"px")}else B=kb(V,c,c,B);n=B;T(f,z);if(e){f="http://www.google.com";if(typeof e=="string"&&(e[Ka](/^http:\/\/[a-z]*\.google\.com/)||e[Ka](/^http:\/\/www\.youtube\.com/)))f=e;e=lb(f,c,"_BLANK");s(e,h.df);T(e,n);T(l,e)}else T(l,n);if(a){a=typeof a=="string"?p.getElementById(a):a;fb(a);T(a,d)}return a=d};O(m[F].a,"getBranding",m[F].a.qf);
m[F].a.setOnLoadCallback=function(a,d){m.setOnLoadCallback(a,d)};O(m[F].a,"setOnLoadCallback",m[F].a.setOnLoadCallback);var Ib;function Hb(a){Ib||(Ib=p[H]("DIV"));Ib[v](a);t(Ib,"")}m[F].a[x].of=function(a){var d=this.jb;if(a)d=a;a={};var e=W(this.ia());Z(e,"gs-result");Z(e,"gs-error-result");d=U(d,"gs-snippet");T(e,d);a.html=e;return a};m[F].a[x].pf=function(a){var d=this.pb;if(a)d=a;a={};var e=W(this.ia());Z(e,"gs-result");Z(e,"gs-no-results-result");d=U(d,"gs-snippet");T(e,d);a.html=e;return a};
j("google.search.CurrentLocale",ea);j("google.search.ShortDatePattern",aa);m[F].q=function(){m[F].a[G](this);this.w="blog";this.Aa="/GblogSearch";this.ma="http://blogsearch.google.com/blogsearch";this.l=c;this.N=g;this.Sa=b;this.fa=eb(this,m[F].q[x].na);this.Ra="gsc-blogConfig";this.n=c};N("google.search.BlogSearch",m[F].q);Xa(m[F].q,m[F].a);m[F].q.B="GblogSearch";O(m[F].q,"RESULT_CLASS",m[F].q.B);m[F].q.m=[];m[F].q.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[F].q.m[l];m[F].q.m[l]=c;a.V(d,e,f,h)};O(m[F].q,"RawCompletion",m[F].q.I);
m[F].q[x].ha=function(a,d,e,f){e=e==c?m[F].a.ka(m[F].q.m,this):e;d=d==c?"google.search.BlogSearch.RawCompletion":d;f=this.ya(d,e,f);if(a){a=a;if(this.H)a=a+" "+this.H;if(this.l)a=a+" blogurl:"+this.l;a="&q="+i(a);if(this.N)a+="&scoring=d";f+=a;this.u=a}return f};
m[F].q[x].C=function(a){a.html&&delete a.html;var d=W(this.ia());Z(d,"gs-result");var e;e=Y(a.postUrl,a[sa],this.s(),"gs-title");T(d,e);e=new Date(a.publishedDate);e=U(this.Ua(e),"gs-publishedDate");T(d,e);e=new Date(a.publishedDate);e=U(this.lc(e),"gs-relativePublishedDate");T(d,e);e=U(a[Da],"gs-snippet");T(d,e);e=Y(a.blogUrl,a.blogUrl,this.s(),"gs-visibleUrl");T(d,e);a.html=d;this.ta(a.html)};O(m[F].q[x],"createResultHtml",m[F].q[x].C);m[F].q[x].pa=function(a){this.l=a==c||a==""?c:a};
O(m[F].q[x],"setSiteRestriction",m[F].q[x].pa);m[F].q[x].K=function(a){this.N=a==m[F].a.la?b:g};O(m[F].q[x],"setResultOrder",m[F].q[x].K);
m[F].q[x].na=function(a,d){if(d){if(this.n==c){d=W("gsc-configSetting");this.n=qb(c,"0",this.N,"gsc-configSettingCheckbox");T(d,this.n);T(d,U(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=W("gsc-configSettingSubmit");T(e,nb(P[Ja],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else ka(this.n,this.N);this.n[Ma]()}else if(this.n)this.n[ya]?this.K(m[F].a.la):this.K(m[F].a.cb)};m[F].j=function(){m[F].a[G](this);this.w="book";this.Aa="/GbookSearch";this.ma="http://books.google.com/books";this.Ib=g;this.Ec=c};N("google.search.BookSearch",m[F].j);Xa(m[F].j,m[F].a);m[F].j.B="GbookSearch";O(m[F].j,"RESULT_CLASS",m[F].j.B);m[F].j.Nd="user-list";O(m[F].j,"USER_LIST",m[F].j.Nd);m[F].j.Fd=1;O(m[F].j,"TYPE_ALL_BOOKS",m[F].j.Fd);m[F].j.Jd=2;O(m[F].j,"TYPE_FULL_VIEW_BOOKS",m[F].j.Jd);m[F].j.m=[];
m[F].j.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[F].j.m[l];m[F].j.m[l]=c;a.V(d,e,f,h)};O(m[F].j,"RawCompletion",m[F].j.I);m[F].j[x].ha=function(a,d,e,f){e=e==c?m[F].a.ka(m[F].j.m,this):e;d=d==c?"google.search.BookSearch.RawCompletion":d;f=this.ya(d,e,f);if(a){a=a;if(this.H)a=a+" "+this.H;a="&q="+i(a);if(this.Ib)a+="&as_brr=1";if(this.Ec)a=a+"&as_list="+this.Ec;f+=a;this.u=a}return f};
m[F].j[x].C=function(a){a.html&&delete a.html;a.thumbnailHtml=this.gc(a);var d=W(this.ia());Z(d,"gs-result");var e=W("gs-text-box"),f=hb(),h=ib(f,0),l=X(h,"gs-image-box");h=X(h,"gs-text-box");T(l,a.thumbnailHtml[Oa](b));T(h,e);T(d,f);f=Y(a.unescapedUrl,a[sa],this.s(),"gs-title");T(e,f);f=U(P.by+"&nbsp;"+a.authors,"gs-author");T(e,f);f=W("gs-spacer");T(e,f);if(a.publishedYear){f=U(a.publishedYear,"gs-publishedDate");T(e,f)}if(ca(a.pageCount,10)>0){f=U("-&nbsp;"+P["page-count"](a.pageCount),"gs-pageCount");
T(e,f)}f=Y("http://books.google.com","books.google.com",this.s(),"gs-visibleUrl");T(e,f);a.html=d;this.ta(a.html)};O(m[F].j[x],"createResultHtml",m[F].j[x].C);
m[F].j[x].gc=function(a){var d=W("gs-image-box gs-book-image-box"),e=W("gs-row-1"),f=kb("http://books.google.com/googlebooks/pages-trans.gif",c,c,"gs-pages");T(e,f);f=kb("http://books.google.com/googlebooks/p_edge-trans.gif",c,c,"gs-page-edge");T(e,f);T(d,e);e=W("gs-row-2");f=m[F].a.Ya(a.tbWidth,a.tbHeight,this.M);f=kb(a.tbUrl,f[C],f[Ua],"gs-image");a=lb(a.unescapedUrl,c,this.s(),"gs-image");s(a,"gs-image");T(a,f);T(e,a);T(d,e);return d};
m[F].j[x].R=function(a,d){if(a==m[F].a.Cb)if(d)if(d==m[F].j.Fd)this.Ib=g;else if(d==m[F].j.Jd)this.Ib=b;else this.R(a,c);else this.Ib=g;else if(a==m[F].j.Nd)this.Ec=d&&d[Ka](/^[a-zA-Z0-9\-_]*$/)?d:c};O(m[F].j[x],"setRestriction",m[F].j[x].R);m[F].c=function(){m[F].a[G](this);this.ne=2;this.w="image";this.Aa="/GimageSearch";this.ma="http://images.google.com/images";this.l=this.xc=this.kc=this.qc=this.oc=this.nc=this.pc=this.Ha=c;this.M={width:112,height:84}};N("google.search.ImageSearch",m[F].c);Xa(m[F].c,m[F].a);m[F].c.B="GimageSearch";O(m[F].c,"RESULT_CLASS",m[F].c.B);m[F].c.wd="restrict-imagesize";O(m[F].c,"RESTRICT_IMAGESIZE",m[F].c.wd);m[F].c.Je=["icon"];O(m[F].c,"IMAGESIZE_SMALL",m[F].c.Je);m[F].c.Ie=["small","medium","large","xlarge"];
O(m[F].c,"IMAGESIZE_MEDIUM",m[F].c.Ie);m[F].c.He=["xxlarge"];O(m[F].c,"IMAGESIZE_LARGE",m[F].c.He);m[F].c.Ge=["huge"];O(m[F].c,"IMAGESIZE_EXTRA_LARGE",m[F].c.Ge);m[F].c.td="restrict-coloration";O(m[F].c,"RESTRICT_COLORIZATION",m[F].c.td);m[F].c.Ic="mono";O(m[F].c,"COLORIZATION_BLACK_AND_WHITE",m[F].c.Ic);m[F].c.Kc="gray";O(m[F].c,"COLORIZATION_GRAYSCALE",m[F].c.Kc);m[F].c.Jc="color";O(m[F].c,"COLORIZATION_COLOR",m[F].c.Jc);m[F].c.sd="restrict-colorfilter";O(m[F].c,"RESTRICT_COLORFILTER",m[F].c.sd);
m[F].c.Tc="red";O(m[F].c,"COLOR_RED",m[F].c.Tc);m[F].c.Qc="orange";O(m[F].c,"COLOR_ORANGE",m[F].c.Qc);m[F].c.Wc="yellow";O(m[F].c,"COLOR_YELLOW",m[F].c.Wc);m[F].c.Pc="green";O(m[F].c,"COLOR_GREEN",m[F].c.Pc);m[F].c.Uc="teal";O(m[F].c,"COLOR_TEAL",m[F].c.Uc);m[F].c.Mc="blue";O(m[F].c,"COLOR_BLUE",m[F].c.Mc);m[F].c.Sc="purple";O(m[F].c,"COLOR_PURPLE",m[F].c.Sc);m[F].c.Rc="pink";O(m[F].c,"COLOR_PINK",m[F].c.Rc);m[F].c.Vc="white";O(m[F].c,"COLOR_WHITE",m[F].c.Vc);m[F].c.Oc="gray";
O(m[F].c,"COLOR_GRAY",m[F].c.Oc);m[F].c.Lc="black";O(m[F].c,"COLOR_BLACK",m[F].c.Lc);m[F].c.Nc="brown";O(m[F].c,"COLOR_BROWN",m[F].c.Nc);m[F].c.vd="restrict-filetype";O(m[F].c,"RESTRICT_FILETYPE",m[F].c.vd);m[F].c.$c="jpg";O(m[F].c,"FILETYPE_JPG",m[F].c.$c);m[F].c.ad="png";O(m[F].c,"FILETYPE_PNG",m[F].c.ad);m[F].c.Zc="gif";O(m[F].c,"FILETYPE_GIF",m[F].c.Zc);m[F].c.Yc="bmp";O(m[F].c,"FILETYPE_BMP",m[F].c.Yc);m[F].c.xd="restrict-imagetype";O(m[F].c,"RESTRICT_IMAGETYPE",m[F].c.xd);m[F].c.cd="face";
O(m[F].c,"IMAGETYPE_FACES",m[F].c.cd);m[F].c.bd="clipart";O(m[F].c,"IMAGETYPE_CLIPART",m[F].c.bd);m[F].c.dd="lineart";O(m[F].c,"IMAGETYPE_LINEART",m[F].c.dd);m[F].c.ed="news";O(m[F].c,"IMAGETYPE_NEWS",m[F].c.ed);m[F].c.fd="photo";O(m[F].c,"IMAGETYPE_PHOTO",m[F].c.fd);m[F].c.rd="restrict";O(m[F].c,"RESTRICT",m[F].c.rd);m[F].c.ud="cc_attribute";O(m[F].c,"RESTRICT_CREATIVE_COMMONS",m[F].c.ud);m[F].c.m=[];m[F].c.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[F].c.m[l];m[F].c.m[l]=c;a.V(d,e,f,h)};
O(m[F].c,"RawCompletion",m[F].c.I);
m[F].c[x].ha=function(a,d,e,f){e=e==c?m[F].a.ka(m[F].c.m,this):e;d=d==c?"google.search.ImageSearch.RawCompletion":d;d=this.ya(d,e,f);if(a){a=a;if(this.H)a=a+" "+this.H;a="&q="+i(a);if(this.Ha)a=a+"&safe="+this.Ha;if(this.pc)a=a+"&imgsz="+i(this.pc);if(this.nc)a=a+"&imgc="+i(this.nc);if(this.oc)a=a+"&imgcolor="+i(this.oc);if(this.qc)a=a+"&imgtype="+i(this.qc);if(this.kc)a=a+"&as_filetype="+i(this.kc);if(this.xc)a=a+"&restrict="+i(this.xc);if(this.l)a=a+"&as_sitesearch="+i(this.l);d+=a;this.u=a;if(f&&
f!=0)this.u=this.u+"&start="+f}return d};
m[F].c[x].C=function(a){a.html&&delete a.html;var d=W(this.ia());Z(d,"gs-result");var e=W("gs-image-box"),f=m[F].a.Ya(a.tbWidth,a.tbHeight,this.M),h=kb(a.tbUrl,f[C],f[Ua],"gs-image");h[E].left=(this.M[C]-f[C])/2+"px";r(h,a.titleNoFormatting+" ("+a.visibleUrl+")");f=lb(a.unescapedUrl,c,this.s(),"gs-image");s(f,"gs-image");T(f,h);T(e,f);T(d,e);e=W("gs-text-box");h=U(a[Da],"gs-snippet");r(h,a.contentNoFormatting);T(e,h);h=U(a[C]+" x "+a[Ua],"gs-size");T(e,h);h=Y(a.originalContextUrl,a.visibleUrl,this.s(),
"gs-visibleUrl");r(h,a.visibleUrl);T(e,h);T(d,e);a.html=d;this.ta(a.html)};O(m[F].c[x],"createResultHtml",m[F].c[x].C);m[F].c[x].pa=function(a){this.l=a};O(m[F].c[x],"setSiteRestriction",m[F].c[x].pa);
m[F].c[x].R=function(a,d){if(a==m[F].a.Tb)this.Ha=d?d==m[F].a.Vb||d==m[F].a.Ub?d:c:c;else if(a==m[F].c.wd)this.pc=d?d.join("|"):c;else if(a==m[F].c.td)this.nc=d?d==m[F].c.Ic||d==m[F].c.Kc||d==m[F].c.Jc?d:c:c;else if(a==m[F].c.sd)this.oc=d?d==m[F].c.Tc||d==m[F].c.Qc||d==m[F].c.Wc||d==m[F].c.Pc||d==m[F].c.Uc||d==m[F].c.Mc||d==m[F].c.Sc||d==m[F].c.Rc||d==m[F].c.Vc||d==m[F].c.Oc||d==m[F].c.Lc||d==m[F].c.Nc?d:c:c;else if(a==m[F].c.vd)this.kc=d?d==m[F].c.$c||d==m[F].c.ad||d==m[F].c.Zc||d==m[F].c.Yc?d:c:
c;else if(a==m[F].c.xd)this.qc=d?d==m[F].c.cd||d==m[F].c.bd||d==m[F].c.dd||d==m[F].c.ed||d==m[F].c.fd?d:c:c;else if(a==m[F].c.rd)this.xc=d?d==m[F].c.ud?d:c:c};O(m[F].c[x],"setRestriction",m[F].c[x].R);m[F].e=function(){m[F].a[G](this);this.aa=c;this.$="San Francisco, CA";this.ea={y:37.77916,x:-122.42009};this.Qa=c;this.ob=b;this.db=g;this.Xa=c;this.Sa=b;this.fa=eb(this,this.na);this.Ra="gsc-locationConfig";this.w="local";this.Aa="/GlocalSearch";this.ma="http://www.google.com/local";this.Oa=this.G=c};N("google.search.LocalSearch",m[F].e);Xa(m[F].e,m[F].a);m[F].e.B="GlocalSearch";O(m[F].e,"RESULT_CLASS",m[F].e.B);m[F].e.Id="blended";O(m[F].e,"TYPE_BLENDED_RESULTS",m[F].e.Id);m[F].e.Ld="kmlonly";
O(m[F].e,"TYPE_KMLONLY_RESULTS",m[F].e.Ld);m[F].e.Md="localonly";O(m[F].e,"TYPE_LOCALONLY_RESULTS",m[F].e.Md);m[F].e.Fc="disabled";O(m[F].e,"ADDRESS_LOOKUP_DISABLED",m[F].e.Fc);m[F].e.Gc="enabled";O(m[F].e,"ADDRESS_LOOKUP_ENABLED",m[F].e.Gc);m[F].e.Cd=17;O(m[F].e,"STATIC_MAP_ZOOM_FARTHEST",m[F].e.Cd);m[F].e.Ue=4;O(m[F].e,"STATIC_MAP_ZOOM_DEFAULT",m[F].e.Ue);m[F].e.Bd=0;O(m[F].e,"STATIC_MAP_ZOOM_CLOSEST",m[F].e.Bd);m[F].e.Zb=8;O(m[F].e,"STATIC_MAP_MAX_POINTS",m[F].e.Zb);m[F].e.Nf=3.141592653589;
m[F].e.mf=6367000;m[F].e.mg=16093;m[F].e.m=[];m[F].e.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[F].e.m[l];m[F].e.m[l]=c;a.resultViewport=d&&d.viewport?d.viewport:c;a.V(d,e,f,h)};O(m[F].e,"RawCompletion",m[F].e.I);
m[F].e[x].ha=function(a,d,e,f){e=e==c?m[F].a.ka(m[F].e.m,this):e;d=d==c?"google.search.LocalSearch.RawCompletion":d;f=this.ya(d,e,f);d="";if(a){d="&q="+i(a);f+=d}this.Ih=c;if(this.aa){var h;if(this.ob){e=this.aa.getCenterLatLng();h=this.aa.getSpanLatLng();a="&sll="+e.y+","+e.x;a+="&sspn="+h[Ua]+","+h[C]}else{e=this.aa.getCenter();h=this.aa.getBounds().toSpan().toUrlValue();a="&sll="+e.y+","+e.x;a+="&sspn="+h}a+=m[F].e.bc(e.y,e.x);f+=a;d+=a}else if(this.ea){a="&sll="+this.ea.y+","+this.ea.x;if(this.Qa)a=
a+"&sspn="+this.Qa.lat+","+this.Qa.lng;a+=m[F].e.bc(this.ea.y,this.ea.x);f+=a;d+=a}else if(this.$){a="&near="+i(this.$);f+=a;d+=a}if(this.db){f+="&nogeocode=t";d+="&nogeocode=t"}if(this.Xa){f+="&mrt="+i(this.Xa);d+="&mrt="+i(this.Xa)}if(d)this.u=d;return f};m[F].e.bc=function(a,d){var e=2*m[F].e.mg/m[F].e.mf*2*m[F].e.Nf,f=d-e,h=a+e;d=d+e;return"&gll="+q[Ca]((a-e)*1000000)+","+q[Ca](f*1000000)+","+q[Ca](h*1000000)+","+q[Ca](d*1000000)+"&llsep=500,500"};O(m[F].e,"centerToGll",m[F].e.bc);
m[F].e[x].C=function(a){a.html&&delete a.html;var d=W(this.ia());Z(d,"gs-result");var e;e=Y(a.url,a[sa],this.s(),"gs-title");T(d,e);if(a.listingType=="kml"&&a[Da]&&a[Da]!=""){e=U(a[Da],"gs-snippet");T(d,e)}var f=W("gs-address");if(a.addressLines&&a.addressLines[w]>0)for(var h=0;h<a.addressLines[w];h++){e=a.addressLines[h];var l="gs-addressLine";if(h==0)l="gs-street gs-addressLine";else if(h==1)l="gs-city gs-addressLine";e=U(e,l);T(f,e)}else{e=U(a.streetAddress,"gs-street");T(f,e);h="";if(a.city!=
""){h=a.city;if(a.region!="")h+=", "}e=U(h,"gs-city");T(f,e);e=U(a.region,"gs-region");T(f,e)}e=U(a.country,"gs-country");T(f,e);T(d,f);if(a.phoneNumbers&&a.phoneNumbers[w]){h=f=c;e=a.phoneNumbers[0];for(var n=0;n<a.phoneNumbers[w];n++){l=a.phoneNumbers[n];if(l[Qa]=="main"){f=l;break}if(l[Qa]==""||l[Qa]=="mobile"&&h==c)h=l}l=f?f:h?h:e;e=U(l.number,"gs-phone");T(d,e)}if(a.ddUrl&&a.ddUrl!=""){e=Y(a.ddUrl,P.directions,this.s(),"gs-directions");T(d,e)}if(a.ddUrlToHere&&a.ddUrlToHere!=""&&a.ddUrlFromHere&&
a.ddUrlFromHere!=""){e=W("gs-directions-to-from");f=U(P["get-directions"]+":","gs-label");e[v](f);f=Y(a.ddUrlToHere,P["to-here"],this.s(),"gs-secondary-link");e[v](f);f=U("-","gs-spacer");e[v](f);f=Y(a.ddUrlFromHere,P["from-here"],this.s(),"gs-secondary-link");e[v](f);T(d,e)}a.html=d;this.ta(a.html)};O(m[F].e[x],"createResultHtml",m[F].e[x].C);
m[F].e[x].te=function(a){if(a.centerAndZoom){this.ob=b;this.aa=a;this.ea=c;this.$="";if(this.G)this.G=c}else if(a.setCenter){this.ob=g;this.aa=a;this.Qa=this.ea=c;this.$="";if(this.G)this.G=c}else if(a.x&&a.y){this.ob=b;this.ea=a;this.aa=this.Qa=c;this.$="";if(this.G)this.G=c}else if(a!=c&&a!=""){this.ob=b;this.aa=c;this.$=a;this.ea=c;if(this.G)this.G=c;var d=new m[F].e;d.xb(this,this.Xe,[d,a]);d[L](a)}};O(m[F].e[x],"setCenterPoint",m[F].e[x].te);
m[F].e[x].Xe=function(a,d){if(a.results&&a.results[w]){var e={};e.y=da(a.results[0].lat);e.x=da(a.results[0].lng);this.ea=e;this.$=d;this.Sa=b;this.aa=c;if(a.resultViewport){d={};d.Xg=da(a.resultViewport.span.lat)/2;d.Yg=da(a.resultViewport.span.lng)/2;this.Qa=d}}};
m[F].e[x].na=function(a,d){if(d){if(this.G==c){d=c;if(this.aa==c){var e=W("gsc-configSetting");this.G=ob(c,"gsc-configSettingInput",this.$==""?c:this.$);T(e,U(P["search-location"],"gsc-configSettingInputLabel"));T(e,this.G);T(a,e);d=this.G}e=W("gsc-configSetting");this.Oa=qb(c,"0",this.db,"gsc-configSettingCheckbox");T(e,this.Oa);T(e,U(P["disable-address-lookup"],"gsc-configSettingCheckboxLabel"));if(d==c)d=this.Oa;var f=U(c,"gsc-configSettingSubmit");T(f,nb(P[Ja],"gsc-configSettingSubmit"));T(e,
f);T(a,e);d[Ma]()}}else{if(this.G){if(this.G[Fa]){this.$=this.G[Fa];this.te(this.$)}this.G=c}if(this.Oa){this.db=this.Oa[ya];this.Oa=c}fb(a)}};m[F].e[x].Wf=function(a){if(a==m[F].e.Fc)this.db=b;else if(a==m[F].e.Gc)this.db=g};O(m[F].e[x],"setAddressLookupMode",m[F].e[x].Wf);m[F].e.pe=function(a,d,e,f){var h=a.staticMapUrl;h=h[D](/&h=\d*/,"&h="+d);h=h[D](/&w=\d*/,"&w="+e);if(f&&f>=m[F].e.Bd&&f<=m[F].e.Cd)h=h[D](/&zl=\d*/,"&zl="+f);return a.staticMapUrl=h};O(m[F].e,"resizeStaticMapUrl",m[F].e.pe);
m[F].e.gf=function(a,d,e,f){var h="",l="http://mt.google.com/mapdata?cc=us&tstyp=5&zl=4&w=150&h=100",n={};n.staticMapUrl=l;l=m[F].e.pe(n,d,e,f);if(f==c)l=l[D](/&zl=\d*/,"");d=a[w];if(d>m[F].e.Zb)d=m[F].e.Zb;for(e=0;e<d;e++){n=a[e];if(n.lat&&n.lng)if(typeof n.lat=="string"){f=da(n.lat);n=da(n.lng)}else{f=n.lat;n=n.lng}else if(n.x&&n.y){f=n.y;n=n.x}else return c;n=n*1000000;f="&Point=b&Point.latitude_e6=__LAT__&Point.longitude_e6=__LNG__&Point.iconid=__ICONID__&Point=e"[D](/__LAT__/,q[Ca](f*1000000));
f=f[D](/__LNG__/,q[Ca](n));n=51+e;if(d==1)n=15;f=f[D](/__ICONID__/,n);h+=f}return l+h};O(m[F].e,"computeStaticMapUrl",m[F].e.gf);m[F].e[x].R=function(a,d){if(a==m[F].a.Cb)if(d){this.Xa=c;this.Xa=d==m[F].e.Id||d==m[F].e.Ld||d==m[F].e.Md?d:c}else this.Xa=c};O(m[F].e[x],"setRestriction",m[F].e[x].R);m[F].k=function(){m[F].a[G](this);this.w="news";this.Aa="/GnewsSearch";this.ma="http://news.google.com/nwshp";this.vh=c;this.Za="site:";this.N=g;this.Sa=b;this.fa=eb(this,this.na);this.Ra="gsc-newsConfig";this.F=this.n=c};N("google.search.NewsSearch",m[F].k);Xa(m[F].k,m[F].a);m[F].k.B="GnewsSearch";O(m[F].k,"RESULT_CLASS",m[F].k.B);m[F].k.qd="GnewsSearch.quote";O(m[F].k,"QUOTE_RESULT_CLASS",m[F].k.qd);m[F].k.m=[];
m[F].k.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[F].k.m[l];m[F].k.m[l]=c;a.V(d,e,f,h)};O(m[F].k,"RawCompletion",m[F].k.I);
m[F].k[x].ha=function(a,d,e,f){e=e==c?m[F].a.ka(m[F].k.m,this):e;d=d==c?"google.search.NewsSearch.RawCompletion":d;d=this.ya(d,e,f);if(a||!a&&this.F){e=c;if(a)e=a;if(this.H)e=e==c?this.H:e+" "+this.H;if(this.l)e=e==c?this.Za+this.l:e+" "+this.Za+this.l;a=e?"&q="+i(e):"";if(this.N)a+="&scoring=d";if(this.F){e="";for(var h in this.F)if(h.charAt(0)==":")e+="&"+this.F[h];a+=e}if(this.l&&this.Za=="source:")d=d[D](/&hl=.*&/,"&hl=en&");d+=a;this.u=a;if(f&&f!=0)this.u=this.u+"&start="+f}return d};
m[F].k[x].C=function(a){a.html&&delete a.html;if(a.GsearchResultClass!=m[F].k.qd){var d=W(this.ia());Z(d,"gs-result");var e;e=Y(a.unescapedUrl,a[sa],this.s(),"gs-title");T(d,e);e=U(a.publisher,"gs-publisher");T(d,e);e=a[Ga][Ba](",");if(e[w]>1){e=U(", "+e[e[w]-1],"gs-location");T(d,e)}e=new Date(a.publishedDate);e=U(" - "+this.Ua(e),"gs-publishedDate");T(d,e);e=new Date(a.publishedDate);e=U(" - "+this.lc(e),"gs-relativePublishedDate");T(d,e);e=U(a[Da],"gs-snippet");T(d,e);if(a.clusterUrl&&a.clusterUrl!=
""){e=Y(a.clusterUrl,P["related-articles"]+"&nbsp;&raquo;",this.s(),"gs-clusterUrl");T(d,e)}a.html=d;this.ta(a.html)}};O(m[F].k[x],"createResultHtml",m[F].k[x].C);m[F].k[x].pa=function(a){if(a==c||a==""){this.l=c;this.Za="site:"}else if(a[Ka]("[./:]")){this.Za="site:";this.l=a}else{this.Za="source:";this.l=a[D](/\s/g,"_")}};O(m[F].k[x],"setSiteRestriction",m[F].k[x].pa);m[F].k[x].K=function(a){this.N=a==m[F].a.la?b:g};O(m[F].k[x],"setResultOrder",m[F].k[x].K);
m[F].k[x].na=function(a,d){if(d){if(this.n==c){d=W("gsc-configSetting");this.n=qb(c,"0",this.N,"gsc-configSettingCheckbox");T(d,this.n);T(d,U(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=W("gsc-configSettingSubmit");T(e,nb(P[Ja],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else ka(this.n,this.N);this.n[Ma]()}else if(this.n)this.n[ya]?this.K(m[F].a.la):this.K(m[F].a.cb)};m[F].k[x].Ze={geo:b,qsid:b,quotesearch:b,topic:b,ned:b,scoring:b,as_mind:b,as_minm:b,as_miny:b,as_maxd:b,as_maxm:b,as_maxy:b};
m[F].k[x].R=function(a,d){if(a==m[F].a.Ma)if(d)for(var e in d){a=d[e];if(typeof this.Ze[e]!="undefined"){this.F=this.F||{};this.F[":"+e]=e+"="+i(a)}}else this.F=c};O(m[F].k[x],"setRestriction",m[F].k[x].R);m[F].h=function(){m[F].a[G](this);this.w="patent";this.Aa="/GpatentSearch";this.ma="http://www.google.com/patents";this.ze="";this.rb=c;this.Sa=b;this.fa=eb(this,this.na);this.Ra="gsc-patentConfig";this.n=c};N("google.search.PatentSearch",m[F].h);Xa(m[F].h,m[F].a);m[F].h.B="GpatentSearch";O(m[F].h,"RESULT_CLASS",m[F].h.B);m[F].h.Gd=1;O(m[F].h,"TYPE_ANY_STATUS",m[F].h.Gd);m[F].h.Kd=2;O(m[F].h,"TYPE_ISSUED_PATENTS",m[F].h.Kd);m[F].h.Hd=3;O(m[F].h,"TYPE_APPLICATIONS",m[F].h.Hd);m[F].h.m=[];
m[F].h.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[F].h.m[l];m[F].h.m[l]=c;a.V(d,e,f,h)};O(m[F].h,"RawCompletion",m[F].h.I);m[F].h[x].ha=function(a,d,e,f){e=e==c?m[F].a.ka(m[F].h.m,this):e;d=d==c?"google.search.PatentSearch.RawCompletion":d;f=this.ya(d,e,f);if(a){a=a;if(this.H)a=a+" "+this.H;a="&q="+i(a)+this.ze;if(this.rb)a+=this.rb;f+=a;this.u=a}return f};
m[F].h[x].C=function(a){a.html&&delete a.html;a.thumbnailHtml=this.gc(a);var d=W(this.ia());Z(d,"gs-result");var e=W("gs-text-box"),f=hb(),h=ib(f,0),l=X(h,"gs-image-box");h=X(h,"gs-text-box");T(l,a.thumbnailHtml[Oa](b));T(h,e);T(d,f);l=Y(a.unescapedUrl,a[sa],this.s(),"gs-title");T(e,l);f=W("gs-patent-info gs-metadata");T(e,f);l=c;l=a.patentNumber?a.patentStatus=="issued"?P["us-pat"]+"&nbsp;"+a.patentNumber:P["us-pat-app"]+"&nbsp;"+a.patentNumber:P["us-pat-app"]+"&nbsp; N/A";l=U(l,"gs-patent-number");
T(f,l);if(a.applicationDate){l=U(" - "+this.Ua(new Date(a.applicationDate)),"gs-publishedDate");T(f,l)}if(a.assignee){l=U(" - "+a.assignee,"gs-author");T(f,l)}l=U(a[Da],"gs-snippet");T(e,l);T(e,l);a.html=d;this.ta(a.html)};O(m[F].h[x],"createResultHtml",m[F].h[x].C);m[F].h[x].gc=function(a){var d=W("gs-patent-image"),e=kb(a.tbUrl,75,100,"gs-image");a=lb(a.unescapedUrl,c,this.s(),"gs-image");s(a,"gs-image");T(a,e);T(d,a);return d};
m[F].h[x].K=function(a){this.rb=a==m[F].a.la?"&scoring=d":a==m[F].a.pd?"&scoring=ad":c};O(m[F].h[x],"setResultOrder",m[F].h[x].K);m[F].h[x].R=function(a,d){if(a==m[F].a.Cb)this.ze=d?d==m[F].h.Gd?"":d==m[F].h.Kd?"&as_psrg=1":d==m[F].h.Hd?"&as_psra=1":"":""};O(m[F].h[x],"setRestriction",m[F].h[x].R);
m[F].h[x].na=function(a,d){if(d){var e=g;if(this.rb&&this.rb=="&scoring=d")e=b;if(this.n==c){d=W("gsc-configSetting");this.n=qb(c,"0",e,"gsc-configSettingCheckbox");T(d,this.n);T(d,U(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));e=W("gsc-configSettingSubmit");T(e,nb(P[Ja],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else ka(this.n,e);this.n[Ma]()}else if(this.n)this.n[ya]?this.K(m[F].a.la):this.K(m[F].a.cb)};m[F].A=function(){this.oe=this.Z=m[F].b.Ca;this.i=c;this.M={width:112,height:84};this.Sb={width:100,height:75};this.pb=c};N("google.search.SearcherOptions",m[F].A);m[F].A[x].ve=function(a){switch(a){case m[F].b.Xc:case m[F].b.La:case m[F].b.Ca:this.Z=a;break;default:this.Z=m[F].b.Ca;break}this.oe=this.Z};O(m[F].A[x],"setExpandMode",m[F].A[x].ve);m[F].A[x].bg=function(a){fb(a);this.i=a};O(m[F].A[x],"setRoot",m[F].A[x].bg);m[F].A[x].wb=function(a){this.pb=a};O(m[F].A[x],"setNoResultsString",m[F].A[x].wb);
m[F].A[x].Xf=function(a){if(a>100)a=100;u(this.M,a);ja(this.M,q[wa](a*1.33))};O(m[F].A[x],"setImageResultsTbHeight",m[F].A[x].Xf);m[F].A[x].hg=function(a){if(a>100)a=100;u(this.Sb,a);ja(this.Sb,q[wa](a*1.33))};O(m[F].A[x],"setVideoResultsTbHeight",m[F].A[x].hg);m[F].S=function(){ia(this,c);this.ye=c;this.Y=m[F].b.qa};N("google.search.DrawOptions",m[F].S);m[F].S[x].Yf=function(a){ia(this,a)};O(m[F].S[x],"setInput",m[F].S[x].Yf);
m[F].S[x].cg=function(a){if(a&&typeof a=="string")a=p.getElementById(a);this.ye=a};O(m[F].S[x],"setSearchFormRoot",m[F].S[x].cg);m[F].S[x].ue=function(a){this.Y=a==m[F].b.qa||a==m[F].b.Ka?a:m[F].b.qa};O(m[F].S[x],"setDrawMode",m[F].S[x].ue);
m[F].z=function(a,d,e){this.t=e;this.ec=this.jc=g;this.f=a;this.v=c;this.Sf=R(d,m[F].b[x].Mf,[this]);this.Vf=R(d,m[F].b[x].vc,[this,m[F].z.Yb]);this.Uf=R(d,m[F].b[x].vc,[this,m[F].z.Xb]);this.Tf=R(d,m[F].b[x].vc,[this,m[F].z.Ad]);this.Rf=R(d,m[F].b[x].Lf,[this]);this.Qf=R(d,m[F].b[x].Hf,[this]);this.f.xb(d,m[F].b[x].V,[this]);this.f.W(d.Lb);this.f.vb(d.Ea);this.Q=this.Ta=this.va=this.yc=this.lb=this.Qb=this.i=c;this.nb=b};m[F].z.Wb=0;m[F].z.Yb=1;m[F].z.Xb=2;m[F].z.Ad=3;
m[F].z[x].Bc=function(a){var d="gsc-results-selector ";d+=a==m[F].z.Wb?this.t.Z==m[F].b.Ca?"gsc-one-result-active":this.f.Ga==m[F].a.da?"gsc-more-results-active":"gsc-all-results-active":a==m[F].z.Yb?"gsc-one-result-active":a==m[F].z.Xb?"gsc-more-results-active":"gsc-all-results-active";s(this.yc,d)};
m[F].b=function(a){if(!m[J].KeyVerified)if(m[F].b.me())m[J].KeyVerified=b;else return;this.Lb=m[F].a.da;this.Y=m[F].b.qa;this.Mb=this.i=c;ia(this,c);this.Pb=m[F].b.Db;this.zf=R(this,m[F].b[x].If,[c]);this.Af=R(this,m[F].b[x].Jf,[c]);this.Wa=this.sb=this.zc=this.Kb=c;this.eb=this.Ef=g;this.Ea=m[F].a.bb;this.rc=P.copy;this.d=[];this.yg=[];var d;if(a)for(var e=0;e<a[w];e++){d=new m[F].z(a[e],this,g);this.d[ra](d)}};N("google.search.SearchControl",m[F].b);m[F].b.od=P["no-results"];
O(m[F].b,"NO_RESULTS_DEFAULT_STRING",m[F].b.od);m[F].b.Ed=350;O(m[F].b,"TIMEOUT_SHORT",m[F].b.Ed);m[F].b.Db=500;O(m[F].b,"TIMEOUT_MEDIUM",m[F].b.Db);m[F].b.Dd=700;O(m[F].b,"TIMEOUT_LONG",m[F].b.Dd);m[F].b.Xc=1;O(m[F].b,"EXPAND_MODE_CLOSED",m[F].b.Xc);m[F].b.La=2;O(m[F].b,"EXPAND_MODE_OPEN",m[F].b.La);m[F].b.Ca=3;O(m[F].b,"EXPAND_MODE_PARTIAL",m[F].b.Ca);m[F].b.qa=1;O(m[F].b,"DRAW_MODE_LINEAR",m[F].b.qa);m[F].b.Ka=2;O(m[F].b,"DRAW_MODE_TABBED",m[F].b.Ka);m[F].b.ld="save";
O(m[F].b,"KEEP_LABEL_SAVE",m[F].b.ld);m[F].b.kd="keep";O(m[F].b,"KEEP_LABEL_KEEP",m[F].b.kd);m[F].b.jd="include";O(m[F].b,"KEEP_LABEL_INCLUDE",m[F].b.jd);m[F].b.hd="copy";O(m[F].b,"KEEP_LABEL_COPY",m[F].b.hd);m[F].b.gd="blank";O(m[F].b,"KEEP_LABEL_BLANK",m[F].b.gd);try{m[F].b.appPath=k[Ga].href}catch(Jb){m[F].b.appPath=c}
m[F].b.me=function(){var a=b,d;d=k[Ga].host[Wa]()[Ba](".");if(d[w]<2)d=g;else{var e=d.pop(),f=d.pop();if((f=="igoogle"||f=="gmodules"||f=="googlesyndication")&&e=="com")d=b;else{if(e[w]==2&&d[w]>0)if(vb[f]&&vb[f][e]==1)f=d.pop();d=f=="google"}}if(d)return b;if(m[J].LoadFailure)if(m[J].OriginalAppPath&&m[F].b.appPath){m[J].LoadFailure=g;a=b}m[J].KeyVerified=b;m[J].LoadFailure=g;return a};O(m[F].b,"keyCheck",m[F].b.me);
m[F].b[x].hb=function(a,d){this.ua=b;this.Pa=a;if(d){if(d.includeVerticalAds!=o)this.Ba=d.includeVerticalAds;if(d.includeSideAds!=o)this.Ba=d.includeSideAds;if(d.iframes!=o)this.kb=d.iframes;if(d.useNarrowTopAd!=o)if(this.kb)this.Be=d.useNarrowTopAd;if(d.channel)this.Qd=d.channel;if(d.clientIP)this.Rd=d.clientIP;if(d.safe)this.Sd=d.safe;if(d[Ea])this.Td=d[Ea];if(a=d.adtest||d.debug)this.$b=a;if(d.numTopAds!=o){this.Fa=d.numTopAds;this.Fa=q.max(0,q.min(4,this.Fa))}if(d.numSideAds!=o){this.xa=d.numSideAds;
this.Ba=(this.xa=q.max(0,q.min(8,this.xa)))?b:g}this.se=d.enableSearchCompleteCallback?b:g}m[J][Sa]("hl","afs_ads")};O(m[F].b[x],"enableAds",m[F].b[x].hb);m[F].b[x].Na=function(a,d){d||(d=new m[F].A);a.oa=c;this.d[ra](new m[F].z(a,this,d));if(this.tb(a))this.wf=b;a.ub="gsc"};O(m[F].b[x],"addSearcher",m[F].b[x].Na);
m[F].b[x].Yd=function(a){if(this.d[a].t.i){this.d[a].nb=g;this.d[a].i=this.d[a].t.i;Z(this.d[a].i,"gsc-resultsRoot");$(this.d[a].i,"gsc-resultsbox-visible");Z(this.d[a].i,"gsc-resultsbox-invisible")}else this.d[a].i=W("gsc-resultsRoot");this.d[a].f.Ab&&pb(this.d[a].i,"gsc-resultsRoot-"+this.d[a].f.Ab);if(this.Y==m[F].b.Ka)this.p[a].ga=this.d[a].i;var d=hb(c,c,"gsc-resultsHeader"),e=ib(d,0);this.d[a].Ja=X(e,"gsc-twiddleRegionCell");e=X(e,"gsc-configLabelCell");this.d[a].Qb=U("","gsc-twiddle");T(this.d[a].Ja,
this.d[a].Qb);var f=U(this.d[a].f.tf(),"gsc-title");T(this.d[a].Qb,f);this.d[a].lb=U("","gsc-stats");T(this.d[a].Ja,this.d[a].lb);f=U();var h=U(P.blank,"gsc-result-selector gsc-one-result"),l=U(P.blank,"gsc-result-selector gsc-more-results"),n=U(P.blank,"gsc-result-selector gsc-all-results");r(h,P["show-one-result"]);r(l,P["show-more-results"]);r(n,P["show-all-results"]);T(f,h);T(f,l);T(f,n);na(h,this.d[a].Vf);na(l,this.d[a].Uf);na(n,this.d[a].Tf);this.d[a].yc=f;this.d[a].Bc(m[F].z.Wb);T(this.d[a].Ja,
this.d[a].yc);na(this.d[a].Qb,this.d[a].Sf);if(this.d[a].f.fa){this.d[a].P=gb("","gsc-configLabel");t(this.d[a].P,P.blank);Z(this.d[a].P,"gsc-twiddle-closed");T(e,this.d[a].P);na(this.d[a].P,this.d[a].Rf);r(this.d[a].P,P.settings);this.d[a].va=W("gsc-config");Z(this.d[a].va,this.d[a].f.Ra);this.d[a].Ta=mb("gsc-config");Z(this.d[a].Ta,this.d[a].f.Ra);this.d[a].Ta.onsubmit=this.d[a].Qf;T(this.d[a].va,this.d[a].Ta);oa(this.d[a].va[E],"none")}this.d[a].Q=W("gsc-results");e=this.d[a].f.mc();Z(this.d[a].Q,
e);this.d[a].t.i==c&&T(this.za,this.d[a].i);T(this.d[a].i,d);this.d[a].va&&T(this.d[a].i,this.d[a].va);T(this.d[a].i,this.d[a].Q)};m[F].b[x].Zd=function(a){var d=this.d[a],e={},f=d.f.vf();f=f[D](/ /g,"&nbsp;");e.U=U(f);e.ga=c;e.Ac=d.f;e.w=d.f.w;na(e.U,R(this,this.lg,[a]));this.p[a]=e;T(this.ba,e.U);a="gs-spacer";if(Za("opera"))a+=" gs-spacer-opera";a=gb(" ",a);T(this.ba,a);d.t.ve(m[F].b.La)};
m[F].b[x].Hb=function(a,d){var e=c,f=c;if(d)if(d.Y){this.Y=d.Y;e=d[A];f=d.ye}else this.Y=m[F].b.qa;else this.Y=m[F].b.qa;this.i=W("gsc-control");if(e!=c){ia(this,e);this[A].onkeyup=this.zf;this[A].onpaste=this.Af}else{if(f==c)f=this.i;d=new m[F].L(b,f);d.xe(this,this.submit);d.we(this,this.cc);ia(this,d[A]);this.ib&&d.xf()}this.za=W("gsc-resultsbox-invisible");if(this.Y==m[F].b.Ka){this.ba=W("gsc-tabsAreaInvisible");T(this.i,this.ba);this.p=[];for(d=this.J=0;d<this.d[w];d++)this.Zd(d)}this.ca=this.i;
if(this.ua){this.ca=W("gsc-wrapper");this.O=W("gsc-adBlockInvisible");this.T=W("gsc-adBlockVerticalInvisible");T(this.ca,this.O);T(this.i,this.T);T(this.i,this.ca);this.$b&&pb(this.i,"gsc-ad-preview")}T(this.ca,this.za);for(d=0;d<this.d[w];d++){this.Yd(d);if(this.Y==m[F].b.Ka){Z(this.p[d].U,"gsc-tabHeader");Z(this.p[d].ga,"gsc-tabData");if(d==this.J){Z(this.p[d].U,"gsc-tabhActive");Z(this.p[d].ga,"gsc-tabdActive")}else{Z(this.p[d].U,"gsc-tabhInactive");Z(this.p[d].ga,"gsc-tabdInactive")}}}if(a&&typeof a==
"string")a=p.getElementById(a);if(a){a=a;d=this.i;if(a)try{fb(a);a[v](d)}catch(h){}if((a=this.rf())&&a<300){this.Ef=b;Z(this.i,"gsc-narrow")}}};O(m[F].b[x],"draw",m[F].b[x].Hb);m[F].b[x].fg=function(a){switch(a){case m[F].b.Ed:case m[F].b.Db:case m[F].b.Dd:this.Pb=a;break;default:this.Pb=m[F].b.Db;break}};O(m[F].b[x],"setTimeoutInterval",m[F].b[x].fg);
m[F].b[x].$f=function(a,d,e){if(e)switch(e){case m[F].b.ld:case m[F].b.kd:case m[F].b.jd:case m[F].b.hd:case m[F].b.gd:this.rc=P[e];break;default:this.rc=e;break}this.Kb=eb(a,d)};O(m[F].b[x],"setOnKeepCallback",m[F].b[x].$f);M=m[F].b[x];M.tb=function(a){var d=a.w;if(this.ib){if(d=="web"&&a.D!=m[F].g.X)return g;return b}else return d=="blog"||d=="image"?b:g};
M.lg=function(a){if(this.J!=a){$(this.p[this.J].U,"gsc-tabhActive");$(this.p[this.J].ga,"gsc-tabdActive");Z(this.p[this.J].U,"gsc-tabhInactive");Z(this.p[this.J].ga,"gsc-tabdInactive");this.J=a;Z(this.p[this.J].U,"gsc-tabhActive");Z(this.p[this.J].ga,"gsc-tabdActive");$(this.p[this.J].U,"gsc-tabhInactive");$(this.p[this.J].ga,"gsc-tabdInactive");if(this.ua){a=this.p[this.J].Ac;this.tb(a)?this.mb():this.ae()}}};
M.mb=function(){if(this.ua){s(this.O,"gsc-adBlockInvisible");s(this.T,"gsc-adBlockVerticalInvisible");this.Ba&&sb(this.ca,"gsc-thinWrapper")}};M.ae=function(){if(this.ua){this.uc>0?rb(this.O,"gsc-adBlock"):rb(this.O,"gsc-adBlockInvisible");if(this.Ba)if(this.tc>0){s(this.T,"gsc-adBlockVertical");Z(this.ca,"gsc-thinWrapper")}else{s(this.T,"gsc-adBlockVerticalInvisible");$(this.ca,"gsc-thinWrapper")}}};M.submit=function(){this[A][Fa][w]?this[L]():this.cc();return g};O(m[F].b[x],"submit",m[F].b[x].submit);
m[F].b[x].Gb=function(){if(this.ba&&!this.kg&&(!this.ib||this.Pd))s(this.ba,"gsc-tabsArea")};
pa(m[F].b[x],function(a){if(a){a=a;this[A].onfocus&&this[A].onfocus();la(this[A],a)}else a=this[A][Fa];this.Eb=c;if(a[w]){this.eb=g;s(this.za,"gsc-resultsbox-visible");this.Gb();this.Va=m[J].createGuidArg_();var d=this.ua;if(d&&this.wf&&this.Y==m[F].b.qa)d=g;var e=this.Bf();if(e==o&&!this.Pa&&!this.kb)d=g;if(d){d=this.Lb==m[F].a.ra;if(this.Fa==o)this.Fa=d?2:1;var f="w"+this.Fa;if(this.Ba){if(this.xa==o)this.xa=d?4:2;f=f+"n"+this.xa}if(this.kb){d="w"+this.Fa;d=m[J].GoogleApisBase+"/services/ads/afs?q="+
i(a)+"&hl="+i(m[F][K])+"&ad="+i(d)+"&source="+this.d[0].f.ub+"&"+this.Va}else d="http://www.google.com/"+(e?"cse":"search")+"?output=js&num=0&ie=utf8&oe=utf8&q="+i(a)+"&hl="+i(m[F][K])+"&ad="+i(f)+"&js=uds&"+this.Va;if(e)d+="&cx="+e;if(this.Pa)d+="&client="+i(this.Pa);if(this.Qd)d+="&channel="+i(this.Qd);if(this.$b)d+="&adtest=on";if(this.Rd)d+="&ip="+i(this.Rd);if(this.Sd)d+="&adsafe="+i(this.Sd);if(this.Td)d+="&useragent="+i(this.Td);if(this.kb){qa(this.za[E],"hidden");this.Eb=new m[F].ab;this.mb();
t(this.O,"");t(this.T,"");if(cb()||db())d+="&nocache="+_json_cache_defeater_++;d+="&referer="+k[Ga].host;if(this.Fa>0){if(this.Be)d=d[D](/&ad=[^&]*/,"&ad=n1w0");f=this.ee(g);e=d.substring(0,2000);e=e[D](/%\w?$/,"");f.src=e;this.O[v](f)}if(this.Ba&&this.xa>0){e=d[D](/&ad=[^&]*/,"&ad="+("n"+this.xa));d=this.ee(b);e=e.substring(0,2000);e=e[D](/%\w?$/,"");d.src=e;this.T[v](d)}}else{var h=this;k.google_afs_request_done=function(l){h.Gf(l)};bb(d)}}for(e=0;e<this.d[w];e++){if(!this.d[e].nb){$(this.d[e].i,
"gsc-resultsbox-invisible");Z(this.d[e].i,"gsc-resultsbox-visible")}this.zc&&this.zc(this,this.d[e].f,a);if(this.d[e].f.oa)this.d[e].f.oa=c;this.d[e].f.Va=this.Va;this.d[e].f[L](a)}this.Eb&&this.Eb.start(2000)}});O(m[F].b[x],"execute",m[F].b[x][L]);M=m[F].b[x];M.hf=function(a,d){var e=this;return function(f){m[J][Sa]("afsq","1");if(d)e.tc=f;else e.uc=f;e.Df(a,d,f);f=f>0;if(e.ba){var h=e.p[e.J].Ac;if(e.tb(h))f=g}f&&e.ae()}};
M.$e=function(a,d){var e=function(){var f=0;try{var h=a.contentWindow;if(h.frames&&h.frames[w])f=h.frames[0].name}catch(l){}d(f)};if(cb())ha(a,function(){if(a[La]=="loaded"||a[La]=="complete"){ha(a,c);e()}});else ga(a,function(){ga(a,c);e()})};
M.af=function(a,d){var e=function(f){f=f?f:k.event;if(f.source==a.contentWindow){if(k.detachEvent)k.detachEvent("onmessage",e);else k.removeEventListener&&k.removeEventListener("message",e,g);d(f.data)}};if(k.attachEvent)k.attachEvent("onmessage",e);else k.addEventListener&&k.addEventListener("message",e,g)};
M.ee=function(a){var d=p[H]("iframe");d.name="google_afs_ads_frame";ja(d,0);u(d,0);d.frameBorder=0;d.marginWidth=0;d.marginHeight=0;d.vspace=0;d.hspace=0;d.wg="true";d.scrolling="no";qa(d[E],"hidden");a=this.Eb.qg(this.hf(d,a));var e=k;(e.postMessage?e:e[Aa].postMessage?e[Aa]:c)?this.af(d,a):this.$e(d,a);return d};M.Df=function(a,d,e){ja(a,"100%");u(a,"100%");u(a[E],d?e*5.65+3+"em":this.Be?e*5+(cb()?3:2)+"em":e*3+1+"em");if(e>0)qa(a[E],"visible")};
M.Bf=function(){for(var a=0;a<this.d[w];a++){var d=this.d[a].f;if(d.w=="web")if(d.D!=m[F].g.X)if(d.D==m[F].g.gb)return d.l}return c};
M.Gf=function(a){k.google_afs_request_done=c;if(this.O){m[J][Sa]("afsq","1");t(this.O,"");t(this.T,"");this.uc=this.tc=0;if(!a||a[w]<1)this.mb();else{if(!this.ba)for(var d=0;d<this.d[w];d++){var e=this.d[d].f;if(this.tb(e)){this.mb();return}}s(this.O,"gsc-adBlock");e=g;var f=p[H]("h2");d="";if(this.$b)d="*DEBUG* ";d+=P["ads-by-google"];t(f,d);T(this.O,f);var h=a[w];for(d=0;d<h;d++){var l=a[d];if(l[Qa]=="text/wide"){this.uc++;var n=W("gsc-ad"),z=Y(l.url,l.line1,m[F].a.bb);T(n,z);z=p[H]("cite");t(z,
l.visible_url);T(n,z);z=gb();t(z,l.line2);T(n,z);T(this.O,n)}else if(this.Ba){this.tc++;if(!e){e=b;Z(this.ca,"gsc-thinWrapper");T(this.T,f[Oa](b));s(this.T,"gsc-adBlockVertical")}n=W("gsc-ad");z=Y(l.url,l.line1,m[F].a.bb);T(n,z);z=gb();t(z,l.line2+"<br/>"+l.line3);T(n,z);z=p[H]("cite");t(z,l.visible_url);T(n,z);T(this.T,n)}}this.Ba&&!e&&sb(this.ca,"gsc-thinWrapper");if(this.ba){e=this.p[this.J].Ac;this.tb(e)&&this.mb()}this.sb&&this.se&&this.sb(this,"ads")}}};
M.If=function(){var a=this[A][Fa];if(a&&a!=""){this.Wa&&k[ua](this.Wa);this.Wa=k[za](R(this,m[F].b[x][L],[c]),this.Pb)}};M.Jf=function(){this.Wa&&k[ua](this.Wa);this.Wa=k[za](R(this,m[F].b[x][L],[c]),this.Pb)};M.W=function(a){switch(a){case m[F].a.ra:this.Lb=a;break;default:case m[F].a.da:this.Lb=m[F].a.da;break}for(var d=0;d<this.d[w];d++)this.d[d].f.W(a)};O(m[F].b[x],"setResultSetSize",m[F].b[x].W);m[F].b[x].vb=function(a){this.Ea=a;for(var d=0;d<this.d[w];d++)this.d[d].f.vb(a)};
O(m[F].b[x],"setLinkTarget",m[F].b[x].vb);m[F].b[x].wb=function(a){for(var d=0;d<this.d[w];d++)this.d[d].t.wb(a)};O(m[F].b[x],"setNoResultsString",m[F].b[x].wb);M=m[F].b[x];M.Mf=function(a){a.jc?this.Ia(a,g):this.Ia(a,b)};M.Ia=function(a,d,e){if(d){$(a.Ja,"gsc-twiddle-closed");Z(a.Ja,"gsc-twiddle-opened");a.jc=b;oa(a.Q[E],"block")}else{$(a.Ja,"gsc-twiddle-opened");Z(a.Ja,"gsc-twiddle-closed");a.jc=g;oa(a.Q[E],"none");t(a.lb,e?"(0)":"("+a.f.results[w]+")")}};M.Hf=function(a){this.yb(a,g,b);return g};
M.Lf=function(a){if(a.f.Sa)a.ec?this.yb(a,g,b):this.yb(a,b,b)};M.yb=function(a,d,e){if(d){if(a.P&&a.f.fa){Z(a.P,"gsc-twiddle-opened");$(a.P,"gsc-twiddle-closed");t(a.P,P[Ja]);a.ec=b;oa(a.va[E],"block");a.f.fa(a.Ta,b)}}else if(a.P&&a.f.fa){$(a.P,"gsc-twiddle-opened");Z(a.P,"gsc-twiddle-closed");t(a.P,P.blank);a.ec=g;a.f.fa(a.Ta,g);oa(a.va[E],"none");e&&this[L]()}};M.Kf=function(a,d){if(this.Kb){d.f.yf();this.Kb(a)}};M.bf=function(){this.eb=b};O(m[F].b[x],"cancelSearch",m[F].b[x].bf);
m[F].b[x].cc=function(){la(this[A],"");this[A].onblur&&this[A].onblur();s(this.za,"gsc-resultsbox-invisible");this.ba&&rb(this.ba,"gsc-tabsAreaInvisible");this.O&&rb(this.O,"gsc-adBlockInvisible");if(this.T){s(this.T,"gsc-adBlockVerticalInvisible");$(this.ca,"gsc-thinWrapper")}for(var a=0;a<this.d[w];a++){if(!this.d[a].nb){$(this.d[a].i,"gsc-resultsbox-visible");Z(this.d[a].i,"gsc-resultsbox-invisible")}var d=this.d[a];fb(d.Q);d.v=c;this.Ia(d,g,b);this.yb(d,g,g)}};O(m[F].b[x],"clearAllResults",m[F].b[x].cc);
m[F].b[x].V=function(a){if(this.kb&&a==this.d[this.J])qa(this.za[E],"visible");var d,e,f=g,h;if(!this.eb){fb(a.Q);a.v=c;this.Ia(a,g,b);this.yb(a,g,g);a.Bc(m[F].z.Wb);var l=a.f.context,n=this.ba&&l;if(this.ib&&!this.Pd){if(n){h=l[sa];for(e=0;e<this.p[w];e++){d=this.p[e];if(d.w==a.f.w){var z=a.f;if(h&&!a.f.$a)t(d.U,h);break}}}this.Pd=b;this.Gb()}if((d=a.f.promotions)&&d[w]>0)for(e=0;e<d[w];e++){var B=d[e];B.html||a.f.Xd(B);if(B.html){h=W(a.f.mc());Z(h,"gsc-result");var V=B.html[Oa](b);T(h,V);T(a.Q,
h)}}B=a.f.results;if(a.f.jb&&a.f.completionStatus>=400){B=[];B[ra](a.f.of())}else if(B[w]==0&&a.t.pb&&a.f.completionStatus==200){B=[];B[ra](a.f.pf(a.t.pb))}for(e=0;e<B[w];e++){d=B[e];d.html||a.f.C(d);if(d.html){f=b;h=W(a.f.mc());Z(h,"gsc-result");a.f.Ab&&pb(h,"gsc-result-"+a.f.Ab);V=d.html[Oa](b);if(d.GsearchResultClass==m[F].c.B){if(a.t.M)if(a.t.M[C]!=a.f.M[C]||a.t.M[Ua]!=a.f.M[Ua])for(var S=V.getElementsByTagName("img"),xa=0;xa<S[w];xa++)m[F].a.Ya(d.tbWidth,d.tbHeight,a.t.M,S[xa],b)}else if(d.GsearchResultClass==
m[F].r.B)if(a.t.Sb){S=V.getElementsByTagName("img");for(xa=0;xa<S[w];xa++)m[F].a.Ya(d.tbWidth,d.tbHeight,a.t.Sb,S[xa])}T(h,V);if(this.Kb){V=this.rc;S=U("","gsc-keeper");t(S,V);T(h,S);na(S,R(this,m[F].b[x].Kf,[d,a]))}if(e>=a.f.ne){if(!a.v){a.v=W("gsc-expansionArea");T(a.Q,a.v);if(a.t.Z==m[F].b.Ca)oa(a.v[E],"none")}T(a.v,h)}else T(a.Q,h)}}if(!a.v&&a.f[y]){a.v=W("gsc-expansionArea");T(a.Q,a.v)}if(a.v&&a.f.u&&a.f.gwsUrl){h=Y(a.f.gwsUrl,P["more-results"]+"&nbsp;&raquo;",a.f.s(),"gsc-trailing-more-results");
if(a.f[y]){e=W("gsc-cursor-box");d=this.jf(a);e[v](d);a.f[y].currentPageIndex==a.f[y].pages[w]-1&&e[v](h);T(a.v,e)}else T(a.v,h)}if(f){t(a.lb,"("+a.f.results[w]+")");a.t.Z==m[F].b.Ca||a.t.Z==m[F].b.La?this.Ia(a,b):this.Ia(a,g);(e=a.f.ge())&&T(a.Q,e)}else{t(a.lb,"(0)");t(a.Q,"");this.Ia(a,g)}a.t.Z=a.t.oe;this.sb&&this.sb(this,a.f);if(this.ib&&n&&!this.We&&l.facets){a=this[A][Fa];l=l.facets;for(e=0;e<l[w];e++){n=l[e];f=new m[F].g;f.pa(z.l,n.label);f.zb(n.anchor);this.Na(f);f[L](a)}for(e=0;e<this.d[w];e++)if(!this.p[e]){this.Zd(e);
this.Yd(e);Z(this.p[e].U,"gsc-tabHeader");Z(this.p[e].ga,"gsc-tabData");Z(this.p[e].U,"gsc-tabhInactive");Z(this.p[e].ga,"gsc-tabdInactive")}this.We=b}}};O(m[F].b[x],"onSearchComplete",m[F].b[x].V);m[F].b[x].jf=function(a){for(var d=W("gsc-cursor"),e=a.f[y],f=0;f<e.pages[w];f++){var h="gsc-cursor-page";if(f==e.currentPageIndex)h+=" gsc-cursor-current-page";h=U(e.pages[f].label,h);na(h,R(this,m[F].b[x].Pf,[a,f]));d[v](h)}return d};
m[F].b.zd={border:"border",borderColor:"border-color",borderStyle:"border-style",borderWidth:"border-width",borderTop:"border-top",borderTopColor:"border-top-color",borderTopStyle:"border-top-style",borderTopWidth:"border-top-width",borderRight:"border-right",borderRightColor:"border-right-color",borderRightStyle:"border-right-style",borderRightWidth:"border-right-width",borderBottom:"border-bottom",borderBottomColor:"border-bottom-color",borderBottomStyle:"border-bottom-style",borderBottomWidth:"border-bottom-width",
borderLeft:"border-left",borderLeftColor:"border-left-color",borderLeftStyle:"border-left-style",borderLeftWidth:"border-left-width",color:"color",cssFloat:"float",styleFloat:"float",clear:"clear",cursor:"cursor",display:"display",font:"font",fontFamily:"font-family",fontSize:"font-size",fontStyle:"font-style",fontWeight:"font-weight",height:"height",margin:"margin",marginTop:"margin-top",marginRight:"margin-right",marginBottom:"margin-bottom",marginLeft:"margin-left",overflow:"overflow",padding:"padding",
paddingTop:"padding-top",paddingRight:"padding-right",paddingBottom:"padding-bottom",paddingLeft:"padding-left",textAlign:"text-align",textDecoration:"text-decoration",textTransform:"text-transform",verticalAlign:"vertical-align",visibility:"visibility",width:"width"};
m[F].b.ke=function(a,d){if(db())alert("google.search.SearchControl.inlineCurrentStyle is not supported on Safari");else{var e=b;if(d)e=d;if(e)for(d=0;d<a.childNodes[w];d++)m[F].b.ke(a.childNodes[d],b);if(a.nodeType==1){var f,h;d=e=g;if(k[Ia]){f=k[Ia](a,c);e=h=b}else if(a[Na]){f=a[Na];h=g;e=b}if(e){for(var l in f)if(m[F].b.zd[l]){e=m[F].b.zd[l];var n=f[l];if(l=="display"&&n=="none"){t(a,"");d=b}if(f[l]!="")h?a[E].setProperty(e,n):a[E][I](e,n)}if(d)if(!h)a.outerHTML='<div style="display:none"/>'}}}};
O(m[F].b,"inlineCurrentStyle",m[F].b.ke);m[F].b[x].rf=function(a){a=a?a:this.i;var d=c;if(k[Ia])d=k[Ia](a,c);else if(a[Na])d=a[Na];else if(p.defaultView[Ia])d=p.defaultView[Ia](a,c);return d?ca(d[C],10):300};m[F].b[x].xb=function(a,d){this.sb=eb(a,d)};O(m[F].b[x],"setSearchCompleteCallback",m[F].b[x].xb);m[F].b[x].dg=function(a,d){this.zc=eb(a,d)};O(m[F].b[x],"setSearchStartingCallback",m[F].b[x].dg);
m[F].b[x].vc=function(a,d){a.Bc(d);var e=g;switch(d){default:case m[F].z.Yb:if(a.v)oa(a.v[E],"none");break;case m[F].z.Xb:if(a.v)oa(a.v[E],"block");if(a.f.Ga!=m[F].a.da)e=b;a.f.W(m[F].a.da);break;case m[F].z.Ad:if(a.v)oa(a.v[E],"block");if(a.f.Ga!=m[F].a.ra)e=b;a.f.W(m[F].a.ra);break}if(e){d=this[A][Fa];if(d[w]){this.eb=g;s(this.za,"gsc-resultsbox-visible");this.Gb();if(!a.nb){$(a.i,"gsc-resultsbox-invisible");Z(a.i,"gsc-resultsbox-visible")}a.t.Z=m[F].b.La;a.f[L](d)}}};
m[F].b[x].Pf=function(a,d){this.eb=g;s(this.za,"gsc-resultsbox-visible");this.Gb();if(!a.nb){$(a.i,"gsc-resultsbox-invisible");Z(a.i,"gsc-resultsbox-visible")}a.t.Z=m[F].b.La;a.f.ie(d)};
m[F].L=function(a,d,e){var f=mb("gsc-search-box");f.acceptCharset="utf-8";var h=c,l=P["search-uc"],n=P[F];if(e){if(e.buttonText)n=l=e.buttonText;if(e.clickableBrandingUrl){h="http://www.google.com";if(typeof e.clickableBrandingUrl=="string"&&e.clickableBrandingUrl[Ka](/^http:\/\/[a-z]*\.google\.com/))h=e.clickableBrandingUrl;h=lb(h,c,"_BLANK");s(h,"gsc-branding-clickable")}}this.Mb=nb(l,"gsc-search-button");r(this.Mb,n);if(a){e="gsc-branding-img";this.dc=U(P.blank,"gsc-clear-button");r(this.dc,P["clear-results"])}else e=
"gsc-branding-img-noclear";ia(this,ob(c,"gsc-input",c));this[A].name="search";r(this[A],n);n=hb(c,c,"gsc-search-box");T(f,n);n=ib(n,0);this.le=X(n,"gsc-input");l=X(n,"gsc-search-button");if(a){a=X(n,"gsc-clear-button");T(a,this.dc)}T(this.le,this[A]);T(l,this.Mb);a=hb(c,c,"gsc-branding");T(f,a);n=ib(a,0);this.userDefinedCell=X(n,"gsc-branding-user-defined");a=X(n,"gsc-branding-text");n=X(n,e);l=U(P["powered-by"],"gsc-branding-text");var z=m[J][Ta]+"/css/small-logo.png";e=e;if(cb()){e=W(e);e[E].filter=
'progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+z+'")';ja(e[E],"51px");u(e[E],"15px")}else e=kb(z,c,c,e);e=e;T(a,l);if(h){T(h,e);T(n,h)}else T(n,e);this.re=f;fb(d);T(d,this.re)};N("google.search.SearchForm",m[F].L);m[F].L[x].xe=function(a,d){this.Ae=R(this,this.jg,[this]);this.Nb=R(a,d,[this]);this.re.onsubmit=this.Ae;na(this.Mb,this.Ae)};O(m[F].L[x],"setOnSubmitCallback",m[F].L[x].xe);m[F].L[x].we=function(a,d){na(this.dc,R(a,d,[this]))};O(m[F].L[x],"setOnClearCallback",m[F].L[x].we);
m[F].L[x].jg=function(){var a=this.le.offsetWidth,d=this[A][Fa];this.Nb&&this.Nb();if(cb()){var e=this,f;f=d[w]*8>=a?a-6:"99%";k[za](function(){ja(e[A][E],f)},1)}return g};pa(m[F].L[x],function(a){if(a)la(this[A],a);this.Nb&&this.Nb()});O(m[F].L[x],"execute",m[F].L[x][L]);
m[F].L[x].xf=function(){var a=this[A],d=function(){if(a[Fa]=="")a[E].background="#FFFFFF url(http://www.google.com/coop/intl/"+m[F][K]+"/images/google_custom_search_watermark.gif) left no-repeat"},e=function(){a[E].background="#FFFFFF"};a.onblur=d;a.onfocus=e;d()};m[F].ab=function(){this.wc=0;this.de=g;this.qb=[]};m[F].ab[x].qg=function(a){this.wc++;var d=this;return function(){for(var e=[],f=0;f<arguments[w];++f)e[ra](arguments[f]);if(d.de)this.be(a,e);else{d.qb[ra]([a,e]);d.wc--;d.wc==0&&d.ce()}}};
m[F].ab[x].ce=function(){for(var a=0;a<this.qb[w];a++)this.be(this.qb[a][0],this.qb[a][1]);this.qb=[];this.de=b};m[F].ab[x].be=function(a,d){k[za](function(){a[Ra](c,d)},0)};m[F].ab[x].start=function(a){k[za](R(this,this.ce,[]),a)};m[F].o=function(a,d){m[F].b[G](this);this.ib=b;this.W(m[F].a.ra);this.hb("",{iframes:b});this.fb=new m[F].g;if(a==o){a={crefUrl:"http://www.google.com/coop/tools/autocse?referer="+k[Ga]};this.rg=b}this.fb.pa(a);this.fb.Ob=P.cse;d&&d[m[F].a.Ma]&&this.fb.R(m[F].a.Ma,d[m[F].a.Ma]);this.Na(this.fb);this.wb(m[F].b.od);this.ng=(new Date)[Va]()};N("google.search.CustomSearchControl",m[F].o);Xa(m[F].o,m[F].b);
m[F].o[x].Hb=function(a,d){(d=d)||(d=new m[F].S);d.ue(m[F].b.Ka);if(this.rg&&this.d[w]==1)this.kg=b;m[F].b[x].Hb[G](this,a,d);s(this.i,"gsc-control-cse")};O(m[F].o[x],"draw",m[F].o[x].Hb);
pa(m[F].o[x],function(a){var d=this.i.offsetWidth;$(this.ca,"gsc-thinWrapper");if(d<m[F].o.Oe)this.ua=g;else d<m[F].o.Qe?this.hb(this.Pa,{useNarrowTopAd:b,includeVerticalAds:g}):this.hb(this.Pa,{useNarrowTopAd:g,includeVerticalAds:d>m[F].o.Pe});if((new Date)[Va]()-this.ng<m[F].o.Ce&&this.ua){d=fa(k[Ga].href)[D]("+"," ");var e=fa(a)[D]("+"," ");this.ua=d[Ha](e)!=-1}m[F].b[x][L][G](this,a)});O(m[F].o[x],"execute",m[F].o[x][L]);m[F].o[x].zb=function(a){this.fb.zb(a)};
O(m[F].o[x],"setUserDefinedLabel",m[F].o[x].zb);m[F].o[x].Na=function(a,d){m[F].b[x].Na[G](this,a,d);a.ub="gcsc"};O(m[F].o[x],"addSearcher",m[F].o[x].Na);m[F].o[x].lf=function(){m[F].b[x].hb("",{numTopAds:0,numSideAds:0});this.Pa=c;this.se=g};O(m[F].o[x],"disableAds",m[F].o[x].lf);m[F].o.De="";O(m[F].o,"AUTO_PUBID",m[F].o.De);m[F].o.Oe=250;m[F].o.Qe=500;m[F].o.Pe=800;m[F].o.Ce=500;m[F].r=function(){m[F].a[G](this);this.w="video";this.Aa="/GvideoSearch";this.ma="http://video.google.com/videosearch";this.N=g;this.Sa=b;this.fa=eb(this,this.na);this.Ra="gsc-videoConfig";this.n=c};N("google.search.VideoSearch",m[F].r);Xa(m[F].r,m[F].a);m[F].r.B="GvideoSearch";O(m[F].r,"RESULT_CLASS",m[F].r.B);m[F].r.m=[];m[F].r.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[F].r.m[l];m[F].r.m[l]=c;a.V(d,e,f,h)};O(m[F].r,"RawCompletion",m[F].r.I);
m[F].r[x].ha=function(a,d,e,f){e=e==c?m[F].a.ka(m[F].r.m,this):e;d=d==c?"google.search.VideoSearch.RawCompletion":d;d=this.ya(d,e,f);if(a){a=a;if(this.H)a=a+" "+this.H;a="&q="+i(a);if(this.N)a+="&scoring=d";d+=a;this.u=a;if(f&&f!=0)this.u=this.u+"&start="+f}return d};
m[F].r[x].C=function(a){a.html&&delete a.html;var d=W(this.ia());Z(d,"gs-result");var e=W("gs-image-box"),f=W("gs-text-box"),h=hb(),l=ib(h,0),n=X(l,"gs-image-box");l=X(l,"gs-text-box");T(n,e);T(l,f);T(d,h);h=m[F].a.Ya(a.tbWidth,a.tbHeight,this.M);h=kb(a.tbUrl,h[C],h[Ua],"gs-image");n=lb(a.url,c,this.s(),"gs-image");s(n,"gs-image");T(n,h);T(e,n);e=Y(a.url,a[sa],this.s(),"gs-title");T(f,e);e=U(a[Da],"gs-snippet");if(cb())u(e[E],"2.6em");T(f,e);e=U(this.Ua(new Date(a.published)),"gs-publishedDate");
T(f,e);e=Y("http://"+a.publisher,a.publisher,this.s(),"gs-publisher");T(f,e);a.html=d;this.ta(a.html)};O(m[F].r[x],"createResultHtml",m[F].r[x].C);
m[F].r.kf=function(a,d){var e=c;if(a.playUrl&&a.playUrl!=""){e=a.playUrl;var f="gsc-video-player";if(d)f=d;if(Za("opera")){var h=p[H]("object");s(h,f);h[I]("type","application/x-shockwave-flash");h[I]("data",e)}else{h=p[H]("embed");s(h,f);h[I]("type","application/x-shockwave-flash");h[I]("src",e);if(a.videoType)a.videoType=="Google"?h[I]("bgcolor","#000000"):h[I]("wmode","transparent");else h[I]("bgcolor","#000000")}e=W(d);e[v](h)}return e};O(m[F].r,"createPlayer",m[F].r.kf);
m[F].r[x].K=function(a){this.N=a==m[F].a.la?b:g};O(m[F].r[x],"setResultOrder",m[F].r[x].K);m[F].r[x].na=function(a,d){if(d){if(this.n==c){d=W("gsc-configSetting");this.n=qb(c,"0",this.N,"gsc-configSettingCheckbox");T(d,this.n);T(d,U(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=W("gsc-configSettingSubmit");T(e,nb(P[Ja],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else ka(this.n,this.N);this.n[Ma]()}else if(this.n)this.n[ya]?this.K(m[F].a.la):this.K(m[F].a.cb)};m[F].g=function(){m[F].a[G](this);this.w="web";this.Aa="/GwebSearch";this.ma="http://www.google.com/search";this.l=c;this.D=m[F].g.X;this.F=this.Ha=this.wa=this.ic=this.Da=c};N("google.search.WebSearch",m[F].g);Xa(m[F].g,m[F].a);m[F].g.B="GwebSearch";O(m[F].g,"RESULT_CLASS",m[F].g.B);m[F].g.gb="cx";O(m[F].g,"cxRestriction_CX",m[F].g.gb);m[F].g.Fb="cref";O(m[F].g,"cxRestriction_CREF",m[F].g.Fb);m[F].g.X="none";O(m[F].g,"cxRestriction_NONE",m[F].g.X);m[F].g.m=[];
m[F].g.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[F].g.m[l];m[F].g.m[l]=c;a.V(d,e,f,h)};O(m[F].g,"RawCompletion",m[F].g.I);m[F].g[x].pg=function(a){return a[D](/\s+$/,"")[D](/^\s+/,"")};m[F].g[x].Ff=function(a){a=this.pg(a);return a[D](/\s+/g,"_")[Wa]()};
m[F].g[x].ha=function(a,d,e,f){e=e==c?m[F].a.ka(m[F].g.m,this):e;if(this.D==m[F].g.X&&this.rh==m[F].a.Bb)throw createException("The resultset size google.search.Search.FILTERED_CSE_RESULTSET can  only be used for querying filtered Custom Search Engines.");d=d==c?"google.search.WebSearch.RawCompletion":d;d=this.ya(d,e,f);if(a){a=a;if(this.H)a=a+" "+this.H;if(this.l&&this.D!=m[F].g.X&&this.ic){e=this.ic;var h=a;if(this.Da!=c)h=a+" more:"+this.Da;e=e[D](/__HL__/,m[F][K]);this.wa=e=e[D](/__QUERY__/,i(h))}if(this.l&&
this.D==m[F].g.X)a=a+" site:"+this.l;e="";if(this.l&&this.D!=m[F].g.X){if(this.D==m[F].g.gb)e=e+"&cx="+this.l;else if(this.D==m[F].g.Fb)e=e+"&cref="+i(this.l);if(this.Da!=c)a=a+" more:"+this.Da}e=e+"&q="+i(a);if(this.Ha)e=e+"&safe="+this.Ha;if(this.F)e+=this.F;d+=e;this.u=e;if(f&&f!=0)this.u=this.u+"&start="+f}if(k.google[J].GoogleLocale)d+="&gl="+i(k.google[J].GoogleLocale);return d};
m[F].g[x].Xd=function(a){a.html&&delete a.html;var d=W("gs-promotion");Z(d,"gs-result");var e=Y(a.url,a[sa],this.s(),"gs-title");T(d,e);e=hb(0,0);var f=ib(e,0),h;T(d,e);if(a.image){e=a.image;e=kb(e.url,e[C],e[Ua],"gs-promotion-image");h=jb("gs-promotion-image-td");T(h,e);T(f,h)}if(a.bodyLines){h=jb();var l=W();T(f,h);T(h,l);f=a.bodyLines;for(h=0;h<f[w];h++){e=f[h];var n=e[sa],z=e.url,B=e.visibleUrl;e=W("gs-snippet");if(z&&B){z=lb(z,B,this.s(),"gs-title");T(e,z)}n&&T(e,p.createTextNode(n?n:""));T(l,
e)}}e=U(a.visibleUrl,"gs-visibleUrl");T(l,e);Z(e,"gs-visibleUrl-short");a.html=d};O(m[F].g[x],"createPromotionHtml",m[F].g[x].Xd);m[F].g[x].$d=function(a,d,e,f){var h=W("gs-image-box gs-web-image-box");if(e==o)e=100;a=kb(a,e,f,"gs-image");d=lb(d,c,this.s());s(d,"gs-image");T(d,a);T(h,d);return h};m[F].g[x].Ud=function(a,d){if(d.url){var e=Y(d.url,d.label||"",this.s(),"gs-action");d["class"]&&pb(e,d["class"]);a.actionHtml||(a.actionHtml=W("gs-actions"));T(a.actionHtml,e)}};
m[F].g[x].C=function(a){a.html&&delete a.html;a.thumbnailHtml&&delete a.thumbnailHtml;a.actionHtml&&delete a.actionHtml;var d=W(this.ia());Z(d,"gs-result");if(a.richSnippet){var e=a.richSnippet;if(e.thumbnail&&e.thumbnail.src)a.thumbnailHtml=this.$d(e.thumbnail.src,a.unescapedUrl,e.thumbnail[C],e.thumbnail[Ua]);else if(e[Aa]&&e[Aa].thumbnailUrl)a.thumbnailHtml=this.$d(e[Aa].thumbnailUrl,a.unescapedUrl);if(e[Pa])if(e[Pa][w]&&e[Pa][0])for(var f=0;f<e[Pa][w];f++)this.Ud(a,e[Pa][f]);else this.Ud(a,e[Pa]);
a.thumbnailHtml&&T(d,a.thumbnailHtml[Oa](b))}e=Y(a.unescapedUrl,a[sa],this.s(),"gs-title");T(d,e);e=U(a[Da],"gs-snippet");T(d,e);e=U(a.visibleUrl,"gs-visibleUrl");T(d,e);Z(e,"gs-visibleUrl-short");e=a.unescapedUrl[Ha](a.visibleUrl);f=a.visibleUrl;if(e!=-1&&e!=0)f=a.unescapedUrl.substring(e);e=U(f,"gs-visibleUrl");Z(e,"gs-visibleUrl-long");T(d,e);a.actionHtml&&T(d,a.actionHtml[Oa](b));a.html=d;this.ta(a.html)};O(m[F].g[x],"createResultHtml",m[F].g[x].C);
m[F].g[x].pa=function(a,d,e){this.jb=this.wa=c;var f=g;if(a==c||typeof a=="string"&&a==""){f=g;this.l=c;this.D=m[F].g.X;this.jb=this.Da=c}else if(typeof a=="string")if(f=a[Ka](/(^partner-pub-\d*:.*)|(^\d{21}:.*)/)){this.l=a;this.D=m[F].g.gb}else{this.l=a;this.D=m[F].g.X}else if(a.siteUrl){f=g;this.l=a.siteUrl}else if(a.cseId){f=b;this.l=a.cseId;this.D=m[F].g.gb}else if(a.crefUrl){f=b;this.l=a.crefUrl;this.D=m[F].g.Fb;this.jb=P["linked-cse-error-results"]}else{f=g;this.l=c;this.D=m[F].g.X;this.Da=
c}if(f){if(d)this.Da=this.Ff(d);if(e)if(e[Ka](/__HL__/)&&e[Ka](/__QUERY__/))this.ic=e;if(this.D==m[F].g.Fb)if(!this.l[Ka](/^http:\/\/www\.google\.com\/coop\/tools\/autocse\?referer=/))(new Image).src="http://www.google.com/cse/tools/ping?cref="+i(this.l)+"&nocache="+Number(new Date)}};O(m[F].g[x],"setSiteRestriction",m[F].g[x].pa);
m[F].g[x].R=function(a,d){if(a==m[F].a.Tb)this.Ha=d?d==m[F].a.Vb||d==m[F].a.Ub||d==m[F].a.yd?d:c:c;if(a==m[F].a.Ma)if(d)for(var e in d){a=d[e];if(e=="lr"||e=="usg"||e=="filter"||e=="gl"||e=="richsnippet"){if(this.F==c)this.F="&";else this.F+="&";this.F+=e+"="+i(a)}}else this.F=c};O(m[F].g[x],"setRestriction",m[F].g[x].R);m[F].g[x].W=function(a){if(m[F].a.Bb==a)this.Ga=m[F].a.Bb;else m[F].a[x].W[G](this,a)};O(m[F].g[x],"setResultSetSize",m[F].g[x].W);if(!m[F].NoOldNames){j("GwebSearch",m[F].g);j("GbookSearch",m[F].j);j("GblogSearch",m[F].q);j("GvideoSearch",m[F].r);j("GnewsSearch",m[F].k);j("GlocalSearch",m[F].e);j("GimageSearch",m[F].c);j("GpatentSearch",m[F].h);j("GSearch",m[F].a);j("GSearchControl",m[F].b);j("GSearchForm",m[F].L);j("GsearcherOptions",m[F].A);j("GdrawOptions",m[F].S)};
google.loader.loaded({"module":"search","version":"1.0","components":["default"]});
google.loader.eval.search = function() {eval(arguments[0])}})()